# SPDX-FileCopyrightText: © 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# SPDX-License-Identifier: MIT

FROM nvcr.io/nvidia/tritonserver:25.04-vllm-python-py3

# Install system dependencies
RUN apt-get update && apt-get --no-install-recommends install -y git tree ffmpeg wget libglib2.0-0 supervisor

# Fix shell and CUDA link
RUN rm /bin/sh && ln -s /bin/bash /bin/sh && ln -s /lib64/libcuda.so.1 /lib64/libcuda.so

# Set workdir
WORKDIR /workspace

# Remove conflicting pre-installed packages if needed
RUN rm -rf /usr/lib/python3/dist-packages/blinker-1.7.0.dist-info

# Install Python dependencies from both requirements files
RUN pip install -v --upgrade --no-build-isolation --no-dependencies sam2==1.1.0 &&
    pip install decord==0.6.0

RUN pip install https://github.com/nvidia-cosmos/cosmos-dependencies/releases/download/v1.1.0/apex-0.1+cu128.torch271-cp312-cp312-linux_x86_64.whl
RUN pip install https://github.com/nvidia-cosmos/cosmos-dependencies/releases/download/v1.1.0/flash_attn-2.6.3+cu128.torch271-cp312-cp312-linux_x86_64.whl
RUN pip install https://github.com/nvidia-cosmos/cosmos-dependencies/releases/download/v1.1.0/natten-0.21.0+cu128.torch271-cp312-cp312-linux_x86_64.whl
RUN pip install https://github.com/nvidia-cosmos/cosmos-dependencies/releases/download/v1.1.0/transformer_engine-1.13.0+cu128.torch271-cp312-cp312-linux_x86_64.whl
RUN pip install https://github.com/nvidia-cosmos/cosmos-dependencies/releases/download/v1.1.0/torch-2.7.1+cu128-cp312-cp312-manylinux_2_28_x86_64.whl
RUN pip install https://github.com/nvidia-cosmos/cosmos-dependencies/releases/download/v1.1.0/torchvision-0.22.1+cu128-cp312-cp312-manylinux_2_28_x86_64.whl


# Install libmagic
RUN apt-get --no-install-recommends install -y libmagic-dev

# Copy all project files and folders into the image
COPY . .

# Install Python dependencies from both requirements files
RUN pip install --no-cache-dir -r requirements_docker.txt && \
    pip install --no-cache-dir -r requirements_server.txt

# Link python explicitly if not already done
RUN ln -sf /usr/bin/python3.12 /usr/bin/python

# Clean up some residuals from the base image
RUN rm -fr /root/.cache/bazel/

# Create necessary directories
RUN mkdir -p storage/jobs_data storage/results logs

# Supervisor will run the API and worker
CMD ["supervisord", "-c", "supervisord.conf"]
