// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Altitude.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 3.3.2).
 */

#ifndef _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_ALTITUDE_H_
#define _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_ALTITUDE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>

#include "AltitudeConfidence.h"
#include "AltitudeValue.h"


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(ALTITUDE_SOURCE)
#define ALTITUDE_DllAPI __declspec( dllexport )
#else
#define ALTITUDE_DllAPI __declspec( dllimport )
#endif // ALTITUDE_SOURCE
#else
#define ALTITUDE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define ALTITUDE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace etsi_its_cam_msgs {

namespace msg {



/*!
 * @brief This class represents the structure Altitude defined by the user in the IDL file.
 * @ingroup Altitude
 */
class Altitude
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Altitude();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Altitude();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object etsi_its_cam_msgs::msg::Altitude that will be copied.
     */
    eProsima_user_DllExport Altitude(
            const Altitude& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object etsi_its_cam_msgs::msg::Altitude that will be copied.
     */
    eProsima_user_DllExport Altitude(
            Altitude&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object etsi_its_cam_msgs::msg::Altitude that will be copied.
     */
    eProsima_user_DllExport Altitude& operator =(
            const Altitude& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object etsi_its_cam_msgs::msg::Altitude that will be copied.
     */
    eProsima_user_DllExport Altitude& operator =(
            Altitude&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x etsi_its_cam_msgs::msg::Altitude object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Altitude& x) const;

    /*!
     * @brief Comparison operator.
     * @param x etsi_its_cam_msgs::msg::Altitude object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Altitude& x) const;

    /*!
     * @brief This function copies the value in member altitude_value
     * @param _altitude_value New value to be copied in member altitude_value
     */
    eProsima_user_DllExport void altitude_value(
            const etsi_its_cam_msgs::msg::AltitudeValue& _altitude_value);

    /*!
     * @brief This function moves the value in member altitude_value
     * @param _altitude_value New value to be moved in member altitude_value
     */
    eProsima_user_DllExport void altitude_value(
            etsi_its_cam_msgs::msg::AltitudeValue&& _altitude_value);

    /*!
     * @brief This function returns a constant reference to member altitude_value
     * @return Constant reference to member altitude_value
     */
    eProsima_user_DllExport const etsi_its_cam_msgs::msg::AltitudeValue& altitude_value() const;

    /*!
     * @brief This function returns a reference to member altitude_value
     * @return Reference to member altitude_value
     */
    eProsima_user_DllExport etsi_its_cam_msgs::msg::AltitudeValue& altitude_value();


    /*!
     * @brief This function copies the value in member altitude_confidence
     * @param _altitude_confidence New value to be copied in member altitude_confidence
     */
    eProsima_user_DllExport void altitude_confidence(
            const etsi_its_cam_msgs::msg::AltitudeConfidence& _altitude_confidence);

    /*!
     * @brief This function moves the value in member altitude_confidence
     * @param _altitude_confidence New value to be moved in member altitude_confidence
     */
    eProsima_user_DllExport void altitude_confidence(
            etsi_its_cam_msgs::msg::AltitudeConfidence&& _altitude_confidence);

    /*!
     * @brief This function returns a constant reference to member altitude_confidence
     * @return Constant reference to member altitude_confidence
     */
    eProsima_user_DllExport const etsi_its_cam_msgs::msg::AltitudeConfidence& altitude_confidence() const;

    /*!
     * @brief This function returns a reference to member altitude_confidence
     * @return Reference to member altitude_confidence
     */
    eProsima_user_DllExport etsi_its_cam_msgs::msg::AltitudeConfidence& altitude_confidence();

private:

    etsi_its_cam_msgs::msg::AltitudeValue m_altitude_value;
    etsi_its_cam_msgs::msg::AltitudeConfidence m_altitude_confidence;

};

} // namespace msg

} // namespace etsi_its_cam_msgs

#endif // _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_ALTITUDE_H_



