// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CenDsrcTollingZone.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 3.3.2).
 */

#ifndef _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_CENDSRCTOLLINGZONE_H_
#define _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_CENDSRCTOLLINGZONE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>

#include "CenDsrcTollingZoneID.h"
#include "Latitude.h"
#include "Longitude.h"


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(CENDSRCTOLLINGZONE_SOURCE)
#define CENDSRCTOLLINGZONE_DllAPI __declspec( dllexport )
#else
#define CENDSRCTOLLINGZONE_DllAPI __declspec( dllimport )
#endif // CENDSRCTOLLINGZONE_SOURCE
#else
#define CENDSRCTOLLINGZONE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define CENDSRCTOLLINGZONE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace etsi_its_cam_msgs {

namespace msg {



/*!
 * @brief This class represents the structure CenDsrcTollingZone defined by the user in the IDL file.
 * @ingroup CenDsrcTollingZone
 */
class CenDsrcTollingZone
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CenDsrcTollingZone();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CenDsrcTollingZone();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object etsi_its_cam_msgs::msg::CenDsrcTollingZone that will be copied.
     */
    eProsima_user_DllExport CenDsrcTollingZone(
            const CenDsrcTollingZone& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object etsi_its_cam_msgs::msg::CenDsrcTollingZone that will be copied.
     */
    eProsima_user_DllExport CenDsrcTollingZone(
            CenDsrcTollingZone&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object etsi_its_cam_msgs::msg::CenDsrcTollingZone that will be copied.
     */
    eProsima_user_DllExport CenDsrcTollingZone& operator =(
            const CenDsrcTollingZone& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object etsi_its_cam_msgs::msg::CenDsrcTollingZone that will be copied.
     */
    eProsima_user_DllExport CenDsrcTollingZone& operator =(
            CenDsrcTollingZone&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x etsi_its_cam_msgs::msg::CenDsrcTollingZone object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CenDsrcTollingZone& x) const;

    /*!
     * @brief Comparison operator.
     * @param x etsi_its_cam_msgs::msg::CenDsrcTollingZone object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CenDsrcTollingZone& x) const;

    /*!
     * @brief This function copies the value in member protected_zone_latitude
     * @param _protected_zone_latitude New value to be copied in member protected_zone_latitude
     */
    eProsima_user_DllExport void protected_zone_latitude(
            const etsi_its_cam_msgs::msg::Latitude& _protected_zone_latitude);

    /*!
     * @brief This function moves the value in member protected_zone_latitude
     * @param _protected_zone_latitude New value to be moved in member protected_zone_latitude
     */
    eProsima_user_DllExport void protected_zone_latitude(
            etsi_its_cam_msgs::msg::Latitude&& _protected_zone_latitude);

    /*!
     * @brief This function returns a constant reference to member protected_zone_latitude
     * @return Constant reference to member protected_zone_latitude
     */
    eProsima_user_DllExport const etsi_its_cam_msgs::msg::Latitude& protected_zone_latitude() const;

    /*!
     * @brief This function returns a reference to member protected_zone_latitude
     * @return Reference to member protected_zone_latitude
     */
    eProsima_user_DllExport etsi_its_cam_msgs::msg::Latitude& protected_zone_latitude();


    /*!
     * @brief This function copies the value in member protected_zone_longitude
     * @param _protected_zone_longitude New value to be copied in member protected_zone_longitude
     */
    eProsima_user_DllExport void protected_zone_longitude(
            const etsi_its_cam_msgs::msg::Longitude& _protected_zone_longitude);

    /*!
     * @brief This function moves the value in member protected_zone_longitude
     * @param _protected_zone_longitude New value to be moved in member protected_zone_longitude
     */
    eProsima_user_DllExport void protected_zone_longitude(
            etsi_its_cam_msgs::msg::Longitude&& _protected_zone_longitude);

    /*!
     * @brief This function returns a constant reference to member protected_zone_longitude
     * @return Constant reference to member protected_zone_longitude
     */
    eProsima_user_DllExport const etsi_its_cam_msgs::msg::Longitude& protected_zone_longitude() const;

    /*!
     * @brief This function returns a reference to member protected_zone_longitude
     * @return Reference to member protected_zone_longitude
     */
    eProsima_user_DllExport etsi_its_cam_msgs::msg::Longitude& protected_zone_longitude();


    /*!
     * @brief This function copies the value in member cen_dsrc_tolling_zone_id
     * @param _cen_dsrc_tolling_zone_id New value to be copied in member cen_dsrc_tolling_zone_id
     */
    eProsima_user_DllExport void cen_dsrc_tolling_zone_id(
            const etsi_its_cam_msgs::msg::CenDsrcTollingZoneID& _cen_dsrc_tolling_zone_id);

    /*!
     * @brief This function moves the value in member cen_dsrc_tolling_zone_id
     * @param _cen_dsrc_tolling_zone_id New value to be moved in member cen_dsrc_tolling_zone_id
     */
    eProsima_user_DllExport void cen_dsrc_tolling_zone_id(
            etsi_its_cam_msgs::msg::CenDsrcTollingZoneID&& _cen_dsrc_tolling_zone_id);

    /*!
     * @brief This function returns a constant reference to member cen_dsrc_tolling_zone_id
     * @return Constant reference to member cen_dsrc_tolling_zone_id
     */
    eProsima_user_DllExport const etsi_its_cam_msgs::msg::CenDsrcTollingZoneID& cen_dsrc_tolling_zone_id() const;

    /*!
     * @brief This function returns a reference to member cen_dsrc_tolling_zone_id
     * @return Reference to member cen_dsrc_tolling_zone_id
     */
    eProsima_user_DllExport etsi_its_cam_msgs::msg::CenDsrcTollingZoneID& cen_dsrc_tolling_zone_id();


    /*!
     * @brief This function sets a value in member cen_dsrc_tolling_zone_id_is_present
     * @param _cen_dsrc_tolling_zone_id_is_present New value for member cen_dsrc_tolling_zone_id_is_present
     */
    eProsima_user_DllExport void cen_dsrc_tolling_zone_id_is_present(
            bool _cen_dsrc_tolling_zone_id_is_present);

    /*!
     * @brief This function returns the value of member cen_dsrc_tolling_zone_id_is_present
     * @return Value of member cen_dsrc_tolling_zone_id_is_present
     */
    eProsima_user_DllExport bool cen_dsrc_tolling_zone_id_is_present() const;

    /*!
     * @brief This function returns a reference to member cen_dsrc_tolling_zone_id_is_present
     * @return Reference to member cen_dsrc_tolling_zone_id_is_present
     */
    eProsima_user_DllExport bool& cen_dsrc_tolling_zone_id_is_present();

private:

    etsi_its_cam_msgs::msg::Latitude m_protected_zone_latitude;
    etsi_its_cam_msgs::msg::Longitude m_protected_zone_longitude;
    etsi_its_cam_msgs::msg::CenDsrcTollingZoneID m_cen_dsrc_tolling_zone_id;
    bool m_cen_dsrc_tolling_zone_id_is_present{false};

};

} // namespace msg

} // namespace etsi_its_cam_msgs

#endif // _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_CENDSRCTOLLINGZONE_H_



