// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file DeltaLongitude.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_DELTALONGITUDE_H_
#define _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_DELTALONGITUDE_H_


#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(DeltaLongitude_SOURCE)
#define DeltaLongitude_DllAPI __declspec( dllexport )
#else
#define DeltaLongitude_DllAPI __declspec( dllimport )
#endif // DeltaLongitude_SOURCE
#else
#define DeltaLongitude_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define DeltaLongitude_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace etsi_its_cam_msgs {
    namespace msg {
        namespace DeltaLongitude_Constants {
            const int32_t MIN = -131071;
            const int32_t MAX = 131072;
            const int32_t ONE_MICRODEGREE_EAST = 10;
            const int32_t ONE_MICRODEGREE_WEST = -10;
            const int32_t UNAVAILABLE = 131072;
        } // namespace DeltaLongitude_Constants
        /*!
         * @brief This class represents the structure DeltaLongitude defined by the user in the IDL file.
         * @ingroup DELTALONGITUDE
         */
        class DeltaLongitude
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport DeltaLongitude();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~DeltaLongitude();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object etsi_its_cam_msgs::msg::DeltaLongitude that will be copied.
             */
            eProsima_user_DllExport DeltaLongitude(
                    const DeltaLongitude& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object etsi_its_cam_msgs::msg::DeltaLongitude that will be copied.
             */
            eProsima_user_DllExport DeltaLongitude(
                    DeltaLongitude&& x);

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object etsi_its_cam_msgs::msg::DeltaLongitude that will be copied.
             */
            eProsima_user_DllExport DeltaLongitude& operator =(
                    const DeltaLongitude& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object etsi_its_cam_msgs::msg::DeltaLongitude that will be copied.
             */
            eProsima_user_DllExport DeltaLongitude& operator =(
                    DeltaLongitude&& x);

            /*!
             * @brief Comparison operator.
             * @param x etsi_its_cam_msgs::msg::DeltaLongitude object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const DeltaLongitude& x) const;

            /*!
             * @brief Comparison operator.
             * @param x etsi_its_cam_msgs::msg::DeltaLongitude object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const DeltaLongitude& x) const;

            /*!
             * @brief This function sets a value in member value
             * @param _value New value for member value
             */
            eProsima_user_DllExport void value(
                    int32_t _value);

            /*!
             * @brief This function returns the value of member value
             * @return Value of member value
             */
            eProsima_user_DllExport int32_t value() const;

            /*!
             * @brief This function returns a reference to member value
             * @return Reference to member value
             */
            eProsima_user_DllExport int32_t& value();


            /*!
             * @brief This function returns the maximum serialized size of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const etsi_its_cam_msgs::msg::DeltaLongitude& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            int32_t m_value;
        };
    } // namespace msg
} // namespace etsi_its_cam_msgs

#endif // _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_DELTALONGITUDE_H_