// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file EmbarkationStatus.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 3.3.2).
 */

#ifndef _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_EMBARKATIONSTATUS_H_
#define _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_EMBARKATIONSTATUS_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(EMBARKATIONSTATUS_SOURCE)
#define EMBARKATIONSTATUS_DllAPI __declspec( dllexport )
#else
#define EMBARKATIONSTATUS_DllAPI __declspec( dllimport )
#endif // EMBARKATIONSTATUS_SOURCE
#else
#define EMBARKATIONSTATUS_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define EMBARKATIONSTATUS_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace etsi_its_cam_msgs {

namespace msg {



/*!
 * @brief This class represents the structure EmbarkationStatus defined by the user in the IDL file.
 * @ingroup EmbarkationStatus
 */
class EmbarkationStatus
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport EmbarkationStatus();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~EmbarkationStatus();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object etsi_its_cam_msgs::msg::EmbarkationStatus that will be copied.
     */
    eProsima_user_DllExport EmbarkationStatus(
            const EmbarkationStatus& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object etsi_its_cam_msgs::msg::EmbarkationStatus that will be copied.
     */
    eProsima_user_DllExport EmbarkationStatus(
            EmbarkationStatus&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object etsi_its_cam_msgs::msg::EmbarkationStatus that will be copied.
     */
    eProsima_user_DllExport EmbarkationStatus& operator =(
            const EmbarkationStatus& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object etsi_its_cam_msgs::msg::EmbarkationStatus that will be copied.
     */
    eProsima_user_DllExport EmbarkationStatus& operator =(
            EmbarkationStatus&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x etsi_its_cam_msgs::msg::EmbarkationStatus object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const EmbarkationStatus& x) const;

    /*!
     * @brief Comparison operator.
     * @param x etsi_its_cam_msgs::msg::EmbarkationStatus object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const EmbarkationStatus& x) const;

    /*!
     * @brief This function sets a value in member value
     * @param _value New value for member value
     */
    eProsima_user_DllExport void value(
            bool _value);

    /*!
     * @brief This function returns the value of member value
     * @return Value of member value
     */
    eProsima_user_DllExport bool value() const;

    /*!
     * @brief This function returns a reference to member value
     * @return Reference to member value
     */
    eProsima_user_DllExport bool& value();

private:

    bool m_value{false};

};

} // namespace msg

} // namespace etsi_its_cam_msgs

#endif // _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_EMBARKATIONSTATUS_H_



