// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Heading.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Heading.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

etsi_its_cam_msgs::msg::Heading::Heading()
{
    // m_heading_value com.eprosima.fastdds.idl.parser.typecode.StructTypeCode@4650a407

    // m_heading_confidence com.eprosima.fastdds.idl.parser.typecode.StructTypeCode@30135202


}

etsi_its_cam_msgs::msg::Heading::~Heading()
{

}

etsi_its_cam_msgs::msg::Heading::Heading(
        const Heading& x)
{
    m_heading_value = x.m_heading_value;
    m_heading_confidence = x.m_heading_confidence;
}

etsi_its_cam_msgs::msg::Heading::Heading(
        Heading&& x)
{
    m_heading_value = std::move(x.m_heading_value);
    m_heading_confidence = std::move(x.m_heading_confidence);
}

etsi_its_cam_msgs::msg::Heading& etsi_its_cam_msgs::msg::Heading::operator =(
        const Heading& x)
{

    m_heading_value = x.m_heading_value;
    m_heading_confidence = x.m_heading_confidence;

    return *this;
}

etsi_its_cam_msgs::msg::Heading& etsi_its_cam_msgs::msg::Heading::operator =(
        Heading&& x)
{

    m_heading_value = std::move(x.m_heading_value);
    m_heading_confidence = std::move(x.m_heading_confidence);

    return *this;
}

bool etsi_its_cam_msgs::msg::Heading::operator ==(
        const Heading& x) const
{

    return (m_heading_value == x.m_heading_value && m_heading_confidence == x.m_heading_confidence);
}

bool etsi_its_cam_msgs::msg::Heading::operator !=(
        const Heading& x) const
{
    return !(*this == x);
}

size_t etsi_its_cam_msgs::msg::Heading::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += etsi_its_cam_msgs::msg::HeadingValue::getMaxCdrSerializedSize(current_alignment);
    current_alignment += etsi_its_cam_msgs::msg::HeadingConfidence::getMaxCdrSerializedSize(current_alignment);

    return current_alignment - initial_alignment;
}

size_t etsi_its_cam_msgs::msg::Heading::getCdrSerializedSize(
        const etsi_its_cam_msgs::msg::Heading& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += etsi_its_cam_msgs::msg::HeadingValue::getCdrSerializedSize(data.heading_value(), current_alignment);
    current_alignment += etsi_its_cam_msgs::msg::HeadingConfidence::getCdrSerializedSize(data.heading_confidence(), current_alignment);

    return current_alignment - initial_alignment;
}

void etsi_its_cam_msgs::msg::Heading::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_heading_value;
    scdr << m_heading_confidence;

}

void etsi_its_cam_msgs::msg::Heading::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_heading_value;
    dcdr >> m_heading_confidence;
}

/*!
 * @brief This function copies the value in member heading_value
 * @param _heading_value New value to be copied in member heading_value
 */
void etsi_its_cam_msgs::msg::Heading::heading_value(
        const etsi_its_cam_msgs::msg::HeadingValue& _heading_value)
{
    m_heading_value = _heading_value;
}

/*!
 * @brief This function moves the value in member heading_value
 * @param _heading_value New value to be moved in member heading_value
 */
void etsi_its_cam_msgs::msg::Heading::heading_value(
        etsi_its_cam_msgs::msg::HeadingValue&& _heading_value)
{
    m_heading_value = std::move(_heading_value);
}

/*!
 * @brief This function returns a constant reference to member heading_value
 * @return Constant reference to member heading_value
 */
const etsi_its_cam_msgs::msg::HeadingValue& etsi_its_cam_msgs::msg::Heading::heading_value() const
{
    return m_heading_value;
}

/*!
 * @brief This function returns a reference to member heading_value
 * @return Reference to member heading_value
 */
etsi_its_cam_msgs::msg::HeadingValue& etsi_its_cam_msgs::msg::Heading::heading_value()
{
    return m_heading_value;
}
/*!
 * @brief This function copies the value in member heading_confidence
 * @param _heading_confidence New value to be copied in member heading_confidence
 */
void etsi_its_cam_msgs::msg::Heading::heading_confidence(
        const etsi_its_cam_msgs::msg::HeadingConfidence& _heading_confidence)
{
    m_heading_confidence = _heading_confidence;
}

/*!
 * @brief This function moves the value in member heading_confidence
 * @param _heading_confidence New value to be moved in member heading_confidence
 */
void etsi_its_cam_msgs::msg::Heading::heading_confidence(
        etsi_its_cam_msgs::msg::HeadingConfidence&& _heading_confidence)
{
    m_heading_confidence = std::move(_heading_confidence);
}

/*!
 * @brief This function returns a constant reference to member heading_confidence
 * @return Constant reference to member heading_confidence
 */
const etsi_its_cam_msgs::msg::HeadingConfidence& etsi_its_cam_msgs::msg::Heading::heading_confidence() const
{
    return m_heading_confidence;
}

/*!
 * @brief This function returns a reference to member heading_confidence
 * @return Reference to member heading_confidence
 */
etsi_its_cam_msgs::msg::HeadingConfidence& etsi_its_cam_msgs::msg::Heading::heading_confidence()
{
    return m_heading_confidence;
}

size_t etsi_its_cam_msgs::msg::Heading::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool etsi_its_cam_msgs::msg::Heading::isKeyDefined()
{
    return false;
}

void etsi_its_cam_msgs::msg::Heading::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}


