// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LateralAcceleration.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "LateralAcceleration.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

etsi_its_cam_msgs::msg::LateralAcceleration::LateralAcceleration()
{
    // m_lateral_acceleration_value com.eprosima.fastdds.idl.parser.typecode.StructTypeCode@4b1c0397

    // m_lateral_acceleration_confidence com.eprosima.fastdds.idl.parser.typecode.StructTypeCode@72805168


}

etsi_its_cam_msgs::msg::LateralAcceleration::~LateralAcceleration()
{

}

etsi_its_cam_msgs::msg::LateralAcceleration::LateralAcceleration(
        const LateralAcceleration& x)
{
    m_lateral_acceleration_value = x.m_lateral_acceleration_value;
    m_lateral_acceleration_confidence = x.m_lateral_acceleration_confidence;
}

etsi_its_cam_msgs::msg::LateralAcceleration::LateralAcceleration(
        LateralAcceleration&& x)
{
    m_lateral_acceleration_value = std::move(x.m_lateral_acceleration_value);
    m_lateral_acceleration_confidence = std::move(x.m_lateral_acceleration_confidence);
}

etsi_its_cam_msgs::msg::LateralAcceleration& etsi_its_cam_msgs::msg::LateralAcceleration::operator =(
        const LateralAcceleration& x)
{

    m_lateral_acceleration_value = x.m_lateral_acceleration_value;
    m_lateral_acceleration_confidence = x.m_lateral_acceleration_confidence;

    return *this;
}

etsi_its_cam_msgs::msg::LateralAcceleration& etsi_its_cam_msgs::msg::LateralAcceleration::operator =(
        LateralAcceleration&& x)
{

    m_lateral_acceleration_value = std::move(x.m_lateral_acceleration_value);
    m_lateral_acceleration_confidence = std::move(x.m_lateral_acceleration_confidence);

    return *this;
}

bool etsi_its_cam_msgs::msg::LateralAcceleration::operator ==(
        const LateralAcceleration& x) const
{

    return (m_lateral_acceleration_value == x.m_lateral_acceleration_value && m_lateral_acceleration_confidence == x.m_lateral_acceleration_confidence);
}

bool etsi_its_cam_msgs::msg::LateralAcceleration::operator !=(
        const LateralAcceleration& x) const
{
    return !(*this == x);
}

size_t etsi_its_cam_msgs::msg::LateralAcceleration::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += etsi_its_cam_msgs::msg::LateralAccelerationValue::getMaxCdrSerializedSize(current_alignment);
    current_alignment += etsi_its_cam_msgs::msg::AccelerationConfidence::getMaxCdrSerializedSize(current_alignment);

    return current_alignment - initial_alignment;
}

size_t etsi_its_cam_msgs::msg::LateralAcceleration::getCdrSerializedSize(
        const etsi_its_cam_msgs::msg::LateralAcceleration& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += etsi_its_cam_msgs::msg::LateralAccelerationValue::getCdrSerializedSize(data.lateral_acceleration_value(), current_alignment);
    current_alignment += etsi_its_cam_msgs::msg::AccelerationConfidence::getCdrSerializedSize(data.lateral_acceleration_confidence(), current_alignment);

    return current_alignment - initial_alignment;
}

void etsi_its_cam_msgs::msg::LateralAcceleration::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_lateral_acceleration_value;
    scdr << m_lateral_acceleration_confidence;

}

void etsi_its_cam_msgs::msg::LateralAcceleration::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_lateral_acceleration_value;
    dcdr >> m_lateral_acceleration_confidence;
}

/*!
 * @brief This function copies the value in member lateral_acceleration_value
 * @param _lateral_acceleration_value New value to be copied in member lateral_acceleration_value
 */
void etsi_its_cam_msgs::msg::LateralAcceleration::lateral_acceleration_value(
        const etsi_its_cam_msgs::msg::LateralAccelerationValue& _lateral_acceleration_value)
{
    m_lateral_acceleration_value = _lateral_acceleration_value;
}

/*!
 * @brief This function moves the value in member lateral_acceleration_value
 * @param _lateral_acceleration_value New value to be moved in member lateral_acceleration_value
 */
void etsi_its_cam_msgs::msg::LateralAcceleration::lateral_acceleration_value(
        etsi_its_cam_msgs::msg::LateralAccelerationValue&& _lateral_acceleration_value)
{
    m_lateral_acceleration_value = std::move(_lateral_acceleration_value);
}

/*!
 * @brief This function returns a constant reference to member lateral_acceleration_value
 * @return Constant reference to member lateral_acceleration_value
 */
const etsi_its_cam_msgs::msg::LateralAccelerationValue& etsi_its_cam_msgs::msg::LateralAcceleration::lateral_acceleration_value() const
{
    return m_lateral_acceleration_value;
}

/*!
 * @brief This function returns a reference to member lateral_acceleration_value
 * @return Reference to member lateral_acceleration_value
 */
etsi_its_cam_msgs::msg::LateralAccelerationValue& etsi_its_cam_msgs::msg::LateralAcceleration::lateral_acceleration_value()
{
    return m_lateral_acceleration_value;
}
/*!
 * @brief This function copies the value in member lateral_acceleration_confidence
 * @param _lateral_acceleration_confidence New value to be copied in member lateral_acceleration_confidence
 */
void etsi_its_cam_msgs::msg::LateralAcceleration::lateral_acceleration_confidence(
        const etsi_its_cam_msgs::msg::AccelerationConfidence& _lateral_acceleration_confidence)
{
    m_lateral_acceleration_confidence = _lateral_acceleration_confidence;
}

/*!
 * @brief This function moves the value in member lateral_acceleration_confidence
 * @param _lateral_acceleration_confidence New value to be moved in member lateral_acceleration_confidence
 */
void etsi_its_cam_msgs::msg::LateralAcceleration::lateral_acceleration_confidence(
        etsi_its_cam_msgs::msg::AccelerationConfidence&& _lateral_acceleration_confidence)
{
    m_lateral_acceleration_confidence = std::move(_lateral_acceleration_confidence);
}

/*!
 * @brief This function returns a constant reference to member lateral_acceleration_confidence
 * @return Constant reference to member lateral_acceleration_confidence
 */
const etsi_its_cam_msgs::msg::AccelerationConfidence& etsi_its_cam_msgs::msg::LateralAcceleration::lateral_acceleration_confidence() const
{
    return m_lateral_acceleration_confidence;
}

/*!
 * @brief This function returns a reference to member lateral_acceleration_confidence
 * @return Reference to member lateral_acceleration_confidence
 */
etsi_its_cam_msgs::msg::AccelerationConfidence& etsi_its_cam_msgs::msg::LateralAcceleration::lateral_acceleration_confidence()
{
    return m_lateral_acceleration_confidence;
}

size_t etsi_its_cam_msgs::msg::LateralAcceleration::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool etsi_its_cam_msgs::msg::LateralAcceleration::isKeyDefined()
{
    return false;
}

void etsi_its_cam_msgs::msg::LateralAcceleration::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}


