// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LongitudinalAcceleration.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "LongitudinalAcceleration.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

etsi_its_cam_msgs::msg::LongitudinalAcceleration::LongitudinalAcceleration()
{
    // m_longitudinal_acceleration_value com.eprosima.fastdds.idl.parser.typecode.StructTypeCode@301d8120

    // m_longitudinal_acceleration_confidence com.eprosima.fastdds.idl.parser.typecode.StructTypeCode@6d367020


}

etsi_its_cam_msgs::msg::LongitudinalAcceleration::~LongitudinalAcceleration()
{

}

etsi_its_cam_msgs::msg::LongitudinalAcceleration::LongitudinalAcceleration(
        const LongitudinalAcceleration& x)
{
    m_longitudinal_acceleration_value = x.m_longitudinal_acceleration_value;
    m_longitudinal_acceleration_confidence = x.m_longitudinal_acceleration_confidence;
}

etsi_its_cam_msgs::msg::LongitudinalAcceleration::LongitudinalAcceleration(
        LongitudinalAcceleration&& x)
{
    m_longitudinal_acceleration_value = std::move(x.m_longitudinal_acceleration_value);
    m_longitudinal_acceleration_confidence = std::move(x.m_longitudinal_acceleration_confidence);
}

etsi_its_cam_msgs::msg::LongitudinalAcceleration& etsi_its_cam_msgs::msg::LongitudinalAcceleration::operator =(
        const LongitudinalAcceleration& x)
{

    m_longitudinal_acceleration_value = x.m_longitudinal_acceleration_value;
    m_longitudinal_acceleration_confidence = x.m_longitudinal_acceleration_confidence;

    return *this;
}

etsi_its_cam_msgs::msg::LongitudinalAcceleration& etsi_its_cam_msgs::msg::LongitudinalAcceleration::operator =(
        LongitudinalAcceleration&& x)
{

    m_longitudinal_acceleration_value = std::move(x.m_longitudinal_acceleration_value);
    m_longitudinal_acceleration_confidence = std::move(x.m_longitudinal_acceleration_confidence);

    return *this;
}

bool etsi_its_cam_msgs::msg::LongitudinalAcceleration::operator ==(
        const LongitudinalAcceleration& x) const
{

    return (m_longitudinal_acceleration_value == x.m_longitudinal_acceleration_value && m_longitudinal_acceleration_confidence == x.m_longitudinal_acceleration_confidence);
}

bool etsi_its_cam_msgs::msg::LongitudinalAcceleration::operator !=(
        const LongitudinalAcceleration& x) const
{
    return !(*this == x);
}

size_t etsi_its_cam_msgs::msg::LongitudinalAcceleration::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += etsi_its_cam_msgs::msg::LongitudinalAccelerationValue::getMaxCdrSerializedSize(current_alignment);
    current_alignment += etsi_its_cam_msgs::msg::AccelerationConfidence::getMaxCdrSerializedSize(current_alignment);

    return current_alignment - initial_alignment;
}

size_t etsi_its_cam_msgs::msg::LongitudinalAcceleration::getCdrSerializedSize(
        const etsi_its_cam_msgs::msg::LongitudinalAcceleration& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += etsi_its_cam_msgs::msg::LongitudinalAccelerationValue::getCdrSerializedSize(data.longitudinal_acceleration_value(), current_alignment);
    current_alignment += etsi_its_cam_msgs::msg::AccelerationConfidence::getCdrSerializedSize(data.longitudinal_acceleration_confidence(), current_alignment);

    return current_alignment - initial_alignment;
}

void etsi_its_cam_msgs::msg::LongitudinalAcceleration::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_longitudinal_acceleration_value;
    scdr << m_longitudinal_acceleration_confidence;

}

void etsi_its_cam_msgs::msg::LongitudinalAcceleration::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_longitudinal_acceleration_value;
    dcdr >> m_longitudinal_acceleration_confidence;
}

/*!
 * @brief This function copies the value in member longitudinal_acceleration_value
 * @param _longitudinal_acceleration_value New value to be copied in member longitudinal_acceleration_value
 */
void etsi_its_cam_msgs::msg::LongitudinalAcceleration::longitudinal_acceleration_value(
        const etsi_its_cam_msgs::msg::LongitudinalAccelerationValue& _longitudinal_acceleration_value)
{
    m_longitudinal_acceleration_value = _longitudinal_acceleration_value;
}

/*!
 * @brief This function moves the value in member longitudinal_acceleration_value
 * @param _longitudinal_acceleration_value New value to be moved in member longitudinal_acceleration_value
 */
void etsi_its_cam_msgs::msg::LongitudinalAcceleration::longitudinal_acceleration_value(
        etsi_its_cam_msgs::msg::LongitudinalAccelerationValue&& _longitudinal_acceleration_value)
{
    m_longitudinal_acceleration_value = std::move(_longitudinal_acceleration_value);
}

/*!
 * @brief This function returns a constant reference to member longitudinal_acceleration_value
 * @return Constant reference to member longitudinal_acceleration_value
 */
const etsi_its_cam_msgs::msg::LongitudinalAccelerationValue& etsi_its_cam_msgs::msg::LongitudinalAcceleration::longitudinal_acceleration_value() const
{
    return m_longitudinal_acceleration_value;
}

/*!
 * @brief This function returns a reference to member longitudinal_acceleration_value
 * @return Reference to member longitudinal_acceleration_value
 */
etsi_its_cam_msgs::msg::LongitudinalAccelerationValue& etsi_its_cam_msgs::msg::LongitudinalAcceleration::longitudinal_acceleration_value()
{
    return m_longitudinal_acceleration_value;
}
/*!
 * @brief This function copies the value in member longitudinal_acceleration_confidence
 * @param _longitudinal_acceleration_confidence New value to be copied in member longitudinal_acceleration_confidence
 */
void etsi_its_cam_msgs::msg::LongitudinalAcceleration::longitudinal_acceleration_confidence(
        const etsi_its_cam_msgs::msg::AccelerationConfidence& _longitudinal_acceleration_confidence)
{
    m_longitudinal_acceleration_confidence = _longitudinal_acceleration_confidence;
}

/*!
 * @brief This function moves the value in member longitudinal_acceleration_confidence
 * @param _longitudinal_acceleration_confidence New value to be moved in member longitudinal_acceleration_confidence
 */
void etsi_its_cam_msgs::msg::LongitudinalAcceleration::longitudinal_acceleration_confidence(
        etsi_its_cam_msgs::msg::AccelerationConfidence&& _longitudinal_acceleration_confidence)
{
    m_longitudinal_acceleration_confidence = std::move(_longitudinal_acceleration_confidence);
}

/*!
 * @brief This function returns a constant reference to member longitudinal_acceleration_confidence
 * @return Constant reference to member longitudinal_acceleration_confidence
 */
const etsi_its_cam_msgs::msg::AccelerationConfidence& etsi_its_cam_msgs::msg::LongitudinalAcceleration::longitudinal_acceleration_confidence() const
{
    return m_longitudinal_acceleration_confidence;
}

/*!
 * @brief This function returns a reference to member longitudinal_acceleration_confidence
 * @return Reference to member longitudinal_acceleration_confidence
 */
etsi_its_cam_msgs::msg::AccelerationConfidence& etsi_its_cam_msgs::msg::LongitudinalAcceleration::longitudinal_acceleration_confidence()
{
    return m_longitudinal_acceleration_confidence;
}

size_t etsi_its_cam_msgs::msg::LongitudinalAcceleration::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool etsi_its_cam_msgs::msg::LongitudinalAcceleration::isKeyDefined()
{
    return false;
}

void etsi_its_cam_msgs::msg::LongitudinalAcceleration::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}


