// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file PathHistory.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_PATHHISTORY_H_
#define _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_PATHHISTORY_H_

#include "PathPoint.h"

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(PathHistory_SOURCE)
#define PathHistory_DllAPI __declspec( dllexport )
#else
#define PathHistory_DllAPI __declspec( dllimport )
#endif // PathHistory_SOURCE
#else
#define PathHistory_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define PathHistory_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace etsi_its_cam_msgs {
    namespace msg {
        namespace PathHistory_Constants {
            const uint8_t MIN_SIZE = 0;
            const uint8_t MAX_SIZE = 40;
        } // namespace PathHistory_Constants
        /*!
         * @brief This class represents the structure PathHistory defined by the user in the IDL file.
         * @ingroup PATHHISTORY
         */
        class PathHistory
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport PathHistory();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~PathHistory();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object etsi_its_cam_msgs::msg::PathHistory that will be copied.
             */
            eProsima_user_DllExport PathHistory(
                    const PathHistory& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object etsi_its_cam_msgs::msg::PathHistory that will be copied.
             */
            eProsima_user_DllExport PathHistory(
                    PathHistory&& x);

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object etsi_its_cam_msgs::msg::PathHistory that will be copied.
             */
            eProsima_user_DllExport PathHistory& operator =(
                    const PathHistory& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object etsi_its_cam_msgs::msg::PathHistory that will be copied.
             */
            eProsima_user_DllExport PathHistory& operator =(
                    PathHistory&& x);

            /*!
             * @brief Comparison operator.
             * @param x etsi_its_cam_msgs::msg::PathHistory object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const PathHistory& x) const;

            /*!
             * @brief Comparison operator.
             * @param x etsi_its_cam_msgs::msg::PathHistory object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const PathHistory& x) const;

            /*!
             * @brief This function copies the value in member array
             * @param _array New value to be copied in member array
             */
            eProsima_user_DllExport void array(
                    const std::vector<etsi_its_cam_msgs::msg::PathPoint>& _array);

            /*!
             * @brief This function moves the value in member array
             * @param _array New value to be moved in member array
             */
            eProsima_user_DllExport void array(
                    std::vector<etsi_its_cam_msgs::msg::PathPoint>&& _array);

            /*!
             * @brief This function returns a constant reference to member array
             * @return Constant reference to member array
             */
            eProsima_user_DllExport const std::vector<etsi_its_cam_msgs::msg::PathPoint>& array() const;

            /*!
             * @brief This function returns a reference to member array
             * @return Reference to member array
             */
            eProsima_user_DllExport std::vector<etsi_its_cam_msgs::msg::PathPoint>& array();

            /*!
             * @brief This function returns the maximum serialized size of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const etsi_its_cam_msgs::msg::PathHistory& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            std::vector<etsi_its_cam_msgs::msg::PathPoint> m_array;
        };
    } // namespace msg
} // namespace etsi_its_cam_msgs

#endif // _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_PATHHISTORY_H_