// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file PerformanceClass.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 3.3.2).
 */

#ifndef _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_PERFORMANCECLASS_H_
#define _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_PERFORMANCECLASS_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(PERFORMANCECLASS_SOURCE)
#define PERFORMANCECLASS_DllAPI __declspec( dllexport )
#else
#define PERFORMANCECLASS_DllAPI __declspec( dllimport )
#endif // PERFORMANCECLASS_SOURCE
#else
#define PERFORMANCECLASS_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define PERFORMANCECLASS_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace etsi_its_cam_msgs {

namespace msg {

namespace PerformanceClass_Constants {

const uint8_t MIN = 0;
const uint8_t MAX = 7;
const uint8_t UNAVAILABLE = 0;
const uint8_t PERFORMANCE_CLASS_A = 1;
const uint8_t PERFORMANCE_CLASS_B = 2;

} // namespace PerformanceClass_Constants


/*!
 * @brief This class represents the structure PerformanceClass defined by the user in the IDL file.
 * @ingroup PerformanceClass
 */
class PerformanceClass
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport PerformanceClass();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~PerformanceClass();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object etsi_its_cam_msgs::msg::PerformanceClass that will be copied.
     */
    eProsima_user_DllExport PerformanceClass(
            const PerformanceClass& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object etsi_its_cam_msgs::msg::PerformanceClass that will be copied.
     */
    eProsima_user_DllExport PerformanceClass(
            PerformanceClass&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object etsi_its_cam_msgs::msg::PerformanceClass that will be copied.
     */
    eProsima_user_DllExport PerformanceClass& operator =(
            const PerformanceClass& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object etsi_its_cam_msgs::msg::PerformanceClass that will be copied.
     */
    eProsima_user_DllExport PerformanceClass& operator =(
            PerformanceClass&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x etsi_its_cam_msgs::msg::PerformanceClass object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const PerformanceClass& x) const;

    /*!
     * @brief Comparison operator.
     * @param x etsi_its_cam_msgs::msg::PerformanceClass object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const PerformanceClass& x) const;

    /*!
     * @brief This function sets a value in member value
     * @param _value New value for member value
     */
    eProsima_user_DllExport void value(
            uint8_t _value);

    /*!
     * @brief This function returns the value of member value
     * @return Value of member value
     */
    eProsima_user_DllExport uint8_t value() const;

    /*!
     * @brief This function returns a reference to member value
     * @return Reference to member value
     */
    eProsima_user_DllExport uint8_t& value();

private:

    uint8_t m_value{0};

};

} // namespace msg

} // namespace etsi_its_cam_msgs

#endif // _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_PERFORMANCECLASS_H_



