// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file PublicTransportContainer.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_PUBLICTRANSPORTCONTAINER_H_
#define _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_PUBLICTRANSPORTCONTAINER_H_

#include "PtActivation.h"
#include "EmbarkationStatus.h"

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(PublicTransportContainer_SOURCE)
#define PublicTransportContainer_DllAPI __declspec( dllexport )
#else
#define PublicTransportContainer_DllAPI __declspec( dllimport )
#endif // PublicTransportContainer_SOURCE
#else
#define PublicTransportContainer_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define PublicTransportContainer_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace etsi_its_cam_msgs {
    namespace msg {
        /*!
         * @brief This class represents the structure PublicTransportContainer defined by the user in the IDL file.
         * @ingroup PUBLICTRANSPORTCONTAINER
         */
        class PublicTransportContainer
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport PublicTransportContainer();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~PublicTransportContainer();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object etsi_its_cam_msgs::msg::PublicTransportContainer that will be copied.
             */
            eProsima_user_DllExport PublicTransportContainer(
                    const PublicTransportContainer& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object etsi_its_cam_msgs::msg::PublicTransportContainer that will be copied.
             */
            eProsima_user_DllExport PublicTransportContainer(
                    PublicTransportContainer&& x);

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object etsi_its_cam_msgs::msg::PublicTransportContainer that will be copied.
             */
            eProsima_user_DllExport PublicTransportContainer& operator =(
                    const PublicTransportContainer& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object etsi_its_cam_msgs::msg::PublicTransportContainer that will be copied.
             */
            eProsima_user_DllExport PublicTransportContainer& operator =(
                    PublicTransportContainer&& x);

            /*!
             * @brief Comparison operator.
             * @param x etsi_its_cam_msgs::msg::PublicTransportContainer object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const PublicTransportContainer& x) const;

            /*!
             * @brief Comparison operator.
             * @param x etsi_its_cam_msgs::msg::PublicTransportContainer object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const PublicTransportContainer& x) const;

            /*!
             * @brief This function copies the value in member embarkation_status
             * @param _embarkation_status New value to be copied in member embarkation_status
             */
            eProsima_user_DllExport void embarkation_status(
                    const etsi_its_cam_msgs::msg::EmbarkationStatus& _embarkation_status);

            /*!
             * @brief This function moves the value in member embarkation_status
             * @param _embarkation_status New value to be moved in member embarkation_status
             */
            eProsima_user_DllExport void embarkation_status(
                    etsi_its_cam_msgs::msg::EmbarkationStatus&& _embarkation_status);

            /*!
             * @brief This function returns a constant reference to member embarkation_status
             * @return Constant reference to member embarkation_status
             */
            eProsima_user_DllExport const etsi_its_cam_msgs::msg::EmbarkationStatus& embarkation_status() const;

            /*!
             * @brief This function returns a reference to member embarkation_status
             * @return Reference to member embarkation_status
             */
            eProsima_user_DllExport etsi_its_cam_msgs::msg::EmbarkationStatus& embarkation_status();
            /*!
             * @brief This function copies the value in member pt_activation
             * @param _pt_activation New value to be copied in member pt_activation
             */
            eProsima_user_DllExport void pt_activation(
                    const etsi_its_cam_msgs::msg::PtActivation& _pt_activation);

            /*!
             * @brief This function moves the value in member pt_activation
             * @param _pt_activation New value to be moved in member pt_activation
             */
            eProsima_user_DllExport void pt_activation(
                    etsi_its_cam_msgs::msg::PtActivation&& _pt_activation);

            /*!
             * @brief This function returns a constant reference to member pt_activation
             * @return Constant reference to member pt_activation
             */
            eProsima_user_DllExport const etsi_its_cam_msgs::msg::PtActivation& pt_activation() const;

            /*!
             * @brief This function returns a reference to member pt_activation
             * @return Reference to member pt_activation
             */
            eProsima_user_DllExport etsi_its_cam_msgs::msg::PtActivation& pt_activation();
            /*!
             * @brief This function sets a value in member pt_activation_is_present
             * @param _pt_activation_is_present New value for member pt_activation_is_present
             */
            eProsima_user_DllExport void pt_activation_is_present(
                    bool _pt_activation_is_present);

            /*!
             * @brief This function returns the value of member pt_activation_is_present
             * @return Value of member pt_activation_is_present
             */
            eProsima_user_DllExport bool pt_activation_is_present() const;

            /*!
             * @brief This function returns a reference to member pt_activation_is_present
             * @return Reference to member pt_activation_is_present
             */
            eProsima_user_DllExport bool& pt_activation_is_present();


            /*!
             * @brief This function returns the maximum serialized size of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const etsi_its_cam_msgs::msg::PublicTransportContainer& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            etsi_its_cam_msgs::msg::EmbarkationStatus m_embarkation_status;
            etsi_its_cam_msgs::msg::PtActivation m_pt_activation;
            bool m_pt_activation_is_present;
        };
    } // namespace msg
} // namespace etsi_its_cam_msgs

#endif // _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_PUBLICTRANSPORTCONTAINER_H_