// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SpecialTransportContainer.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 3.3.2).
 */

#ifndef _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_SPECIALTRANSPORTCONTAINER_H_
#define _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_SPECIALTRANSPORTCONTAINER_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>

#include "SpecialTransportType.h"
#include "LightBarSirenInUse.h"


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(SPECIALTRANSPORTCONTAINER_SOURCE)
#define SPECIALTRANSPORTCONTAINER_DllAPI __declspec( dllexport )
#else
#define SPECIALTRANSPORTCONTAINER_DllAPI __declspec( dllimport )
#endif // SPECIALTRANSPORTCONTAINER_SOURCE
#else
#define SPECIALTRANSPORTCONTAINER_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define SPECIALTRANSPORTCONTAINER_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace etsi_its_cam_msgs {

namespace msg {



/*!
 * @brief This class represents the structure SpecialTransportContainer defined by the user in the IDL file.
 * @ingroup SpecialTransportContainer
 */
class SpecialTransportContainer
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport SpecialTransportContainer();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~SpecialTransportContainer();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object etsi_its_cam_msgs::msg::SpecialTransportContainer that will be copied.
     */
    eProsima_user_DllExport SpecialTransportContainer(
            const SpecialTransportContainer& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object etsi_its_cam_msgs::msg::SpecialTransportContainer that will be copied.
     */
    eProsima_user_DllExport SpecialTransportContainer(
            SpecialTransportContainer&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object etsi_its_cam_msgs::msg::SpecialTransportContainer that will be copied.
     */
    eProsima_user_DllExport SpecialTransportContainer& operator =(
            const SpecialTransportContainer& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object etsi_its_cam_msgs::msg::SpecialTransportContainer that will be copied.
     */
    eProsima_user_DllExport SpecialTransportContainer& operator =(
            SpecialTransportContainer&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x etsi_its_cam_msgs::msg::SpecialTransportContainer object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const SpecialTransportContainer& x) const;

    /*!
     * @brief Comparison operator.
     * @param x etsi_its_cam_msgs::msg::SpecialTransportContainer object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const SpecialTransportContainer& x) const;

    /*!
     * @brief This function copies the value in member special_transport_type
     * @param _special_transport_type New value to be copied in member special_transport_type
     */
    eProsima_user_DllExport void special_transport_type(
            const etsi_its_cam_msgs::msg::SpecialTransportType& _special_transport_type);

    /*!
     * @brief This function moves the value in member special_transport_type
     * @param _special_transport_type New value to be moved in member special_transport_type
     */
    eProsima_user_DllExport void special_transport_type(
            etsi_its_cam_msgs::msg::SpecialTransportType&& _special_transport_type);

    /*!
     * @brief This function returns a constant reference to member special_transport_type
     * @return Constant reference to member special_transport_type
     */
    eProsima_user_DllExport const etsi_its_cam_msgs::msg::SpecialTransportType& special_transport_type() const;

    /*!
     * @brief This function returns a reference to member special_transport_type
     * @return Reference to member special_transport_type
     */
    eProsima_user_DllExport etsi_its_cam_msgs::msg::SpecialTransportType& special_transport_type();


    /*!
     * @brief This function copies the value in member light_bar_siren_in_use
     * @param _light_bar_siren_in_use New value to be copied in member light_bar_siren_in_use
     */
    eProsima_user_DllExport void light_bar_siren_in_use(
            const etsi_its_cam_msgs::msg::LightBarSirenInUse& _light_bar_siren_in_use);

    /*!
     * @brief This function moves the value in member light_bar_siren_in_use
     * @param _light_bar_siren_in_use New value to be moved in member light_bar_siren_in_use
     */
    eProsima_user_DllExport void light_bar_siren_in_use(
            etsi_its_cam_msgs::msg::LightBarSirenInUse&& _light_bar_siren_in_use);

    /*!
     * @brief This function returns a constant reference to member light_bar_siren_in_use
     * @return Constant reference to member light_bar_siren_in_use
     */
    eProsima_user_DllExport const etsi_its_cam_msgs::msg::LightBarSirenInUse& light_bar_siren_in_use() const;

    /*!
     * @brief This function returns a reference to member light_bar_siren_in_use
     * @return Reference to member light_bar_siren_in_use
     */
    eProsima_user_DllExport etsi_its_cam_msgs::msg::LightBarSirenInUse& light_bar_siren_in_use();

private:

    etsi_its_cam_msgs::msg::SpecialTransportType m_special_transport_type;
    etsi_its_cam_msgs::msg::LightBarSirenInUse m_light_bar_siren_in_use;

};

} // namespace msg

} // namespace etsi_its_cam_msgs

#endif // _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_SPECIALTRANSPORTCONTAINER_H_



