// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Speed.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_SPEED_H_
#define _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_SPEED_H_

#include "SpeedValue.h"
#include "SpeedConfidence.h"

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(Speed_SOURCE)
#define Speed_DllAPI __declspec( dllexport )
#else
#define Speed_DllAPI __declspec( dllimport )
#endif // Speed_SOURCE
#else
#define Speed_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define Speed_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace etsi_its_cam_msgs {
    namespace msg {
        /*!
         * @brief This class represents the structure Speed defined by the user in the IDL file.
         * @ingroup SPEED
         */
        class Speed
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport Speed();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~Speed();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object etsi_its_cam_msgs::msg::Speed that will be copied.
             */
            eProsima_user_DllExport Speed(
                    const Speed& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object etsi_its_cam_msgs::msg::Speed that will be copied.
             */
            eProsima_user_DllExport Speed(
                    Speed&& x);

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object etsi_its_cam_msgs::msg::Speed that will be copied.
             */
            eProsima_user_DllExport Speed& operator =(
                    const Speed& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object etsi_its_cam_msgs::msg::Speed that will be copied.
             */
            eProsima_user_DllExport Speed& operator =(
                    Speed&& x);

            /*!
             * @brief Comparison operator.
             * @param x etsi_its_cam_msgs::msg::Speed object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const Speed& x) const;

            /*!
             * @brief Comparison operator.
             * @param x etsi_its_cam_msgs::msg::Speed object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const Speed& x) const;

            /*!
             * @brief This function copies the value in member speed_value
             * @param _speed_value New value to be copied in member speed_value
             */
            eProsima_user_DllExport void speed_value(
                    const etsi_its_cam_msgs::msg::SpeedValue& _speed_value);

            /*!
             * @brief This function moves the value in member speed_value
             * @param _speed_value New value to be moved in member speed_value
             */
            eProsima_user_DllExport void speed_value(
                    etsi_its_cam_msgs::msg::SpeedValue&& _speed_value);

            /*!
             * @brief This function returns a constant reference to member speed_value
             * @return Constant reference to member speed_value
             */
            eProsima_user_DllExport const etsi_its_cam_msgs::msg::SpeedValue& speed_value() const;

            /*!
             * @brief This function returns a reference to member speed_value
             * @return Reference to member speed_value
             */
            eProsima_user_DllExport etsi_its_cam_msgs::msg::SpeedValue& speed_value();
            /*!
             * @brief This function copies the value in member speed_confidence
             * @param _speed_confidence New value to be copied in member speed_confidence
             */
            eProsima_user_DllExport void speed_confidence(
                    const etsi_its_cam_msgs::msg::SpeedConfidence& _speed_confidence);

            /*!
             * @brief This function moves the value in member speed_confidence
             * @param _speed_confidence New value to be moved in member speed_confidence
             */
            eProsima_user_DllExport void speed_confidence(
                    etsi_its_cam_msgs::msg::SpeedConfidence&& _speed_confidence);

            /*!
             * @brief This function returns a constant reference to member speed_confidence
             * @return Constant reference to member speed_confidence
             */
            eProsima_user_DllExport const etsi_its_cam_msgs::msg::SpeedConfidence& speed_confidence() const;

            /*!
             * @brief This function returns a reference to member speed_confidence
             * @return Reference to member speed_confidence
             */
            eProsima_user_DllExport etsi_its_cam_msgs::msg::SpeedConfidence& speed_confidence();

            /*!
             * @brief This function returns the maximum serialized size of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const etsi_its_cam_msgs::msg::Speed& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            etsi_its_cam_msgs::msg::SpeedValue m_speed_value;
            etsi_its_cam_msgs::msg::SpeedConfidence m_speed_confidence;
        };
    } // namespace msg
} // namespace etsi_its_cam_msgs

#endif // _FAST_DDS_GENERATED_ETSI_ITS_CAM_MSGS_MSG_SPEED_H_