// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SpeedValue.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "SpeedValue.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>







etsi_its_cam_msgs::msg::SpeedValue::SpeedValue()
{
    // m_value com.eprosima.idl.parser.typecode.PrimitiveTypeCode@41477a6d
    m_value = 0;

}

etsi_its_cam_msgs::msg::SpeedValue::~SpeedValue()
{
}

etsi_its_cam_msgs::msg::SpeedValue::SpeedValue(
        const SpeedValue& x)
{
    m_value = x.m_value;
}

etsi_its_cam_msgs::msg::SpeedValue::SpeedValue(
        SpeedValue&& x)
{
    m_value = x.m_value;
}

etsi_its_cam_msgs::msg::SpeedValue& etsi_its_cam_msgs::msg::SpeedValue::operator =(
        const SpeedValue& x)
{

    m_value = x.m_value;

    return *this;
}

etsi_its_cam_msgs::msg::SpeedValue& etsi_its_cam_msgs::msg::SpeedValue::operator =(
        SpeedValue&& x)
{

    m_value = x.m_value;

    return *this;
}

bool etsi_its_cam_msgs::msg::SpeedValue::operator ==(
        const SpeedValue& x) const
{

    return (m_value == x.m_value);
}

bool etsi_its_cam_msgs::msg::SpeedValue::operator !=(
        const SpeedValue& x) const
{
    return !(*this == x);
}

size_t etsi_its_cam_msgs::msg::SpeedValue::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 2 + eprosima::fastcdr::Cdr::alignment(current_alignment, 2);


    return current_alignment - initial_alignment;
}

size_t etsi_its_cam_msgs::msg::SpeedValue::getCdrSerializedSize(
        const etsi_its_cam_msgs::msg::SpeedValue& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 2 + eprosima::fastcdr::Cdr::alignment(current_alignment, 2);


    return current_alignment - initial_alignment;
}

void etsi_its_cam_msgs::msg::SpeedValue::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_value;

}

void etsi_its_cam_msgs::msg::SpeedValue::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_value;
}

/*!
 * @brief This function sets a value in member value
 * @param _value New value for member value
 */
void etsi_its_cam_msgs::msg::SpeedValue::value(
        uint16_t _value)
{
    m_value = _value;
}

/*!
 * @brief This function returns the value of member value
 * @return Value of member value
 */
uint16_t etsi_its_cam_msgs::msg::SpeedValue::value() const
{
    return m_value;
}

/*!
 * @brief This function returns a reference to member value
 * @return Reference to member value
 */
uint16_t& etsi_its_cam_msgs::msg::SpeedValue::value()
{
    return m_value;
}


size_t etsi_its_cam_msgs::msg::SpeedValue::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool etsi_its_cam_msgs::msg::SpeedValue::isKeyDefined()
{
    return false;
}

void etsi_its_cam_msgs::msg::SpeedValue::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
     
}


