language: cpp
compiler: clang

os: linux
dist: trusty
sudo: false

matrix:
  include:

    - env: TEST="Unit Tests"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - g++-7 # we need this one for the libstdc++.
            - clang-5.0
            - ninja-build
            - python
            - python-pip
            - python3
            - python3-pip
            - libboost-python-dev
      install:
        - pip2 install --user setuptools nose2
        - pip3 install --user setuptools nose2
        - make setup
      script:
        - make check ARGS="--all --gtest_args=--gtest_filter=-*_mt"

    - env: TEST="Pylint 2"
      addons:
        apt:
          packages:
            - python
            - python-pip
      install:
        - pip2 install --user -r PythonClient/requirements.txt
        - pip2 install --user pylint
      script:
        - pylint --disable=R,C --rcfile=PythonClient/.pylintrc PythonClient/carla PythonClient/*.py

    - env: TEST="MkDocs"
      install:
        - pip install --user mkdocs
      script:
        - mkdocs build --verbose --clean --strict --site-dir _site

    - env: TEST="AwesomeBot"
      install:
        - gem install awesome_bot
      script:
        - find . -name '*.md' | xargs awesome_bot --allow-dupe --allow-redirect --skip-save-results

notifications:
  email: false
