language: python

os: linux
dist: trusty # xenial is not yet supported.

env: TEST="Pylint"
python:
  - "3.5"
  - "3.6"
  - "2.7"
install:
  - pip install -r PythonClient/requirements.txt
  - pip install pylint
script:
  - pylint --disable=R,C --rcfile=PythonClient/.pylintrc PythonClient/carla PythonClient/*.py

matrix:
  include:

    - env: TEST="CppCheck"
      install: true
      addons:
        apt:
          packages:
            - cppcheck
      script:
        - cppcheck . -iBuild -i.pb.cc --error-exitcode=1 --enable=warning --inline-suppr --quiet

    - env: TEST="MkDocs"
      install:
        - pip install mkdocs
      script:
        - mkdocs build --verbose --clean --strict --site-dir _site

    - env: TEST="AwesomeBot"
      install:
        - gem install awesome_bot
      script:
        - find . -name '*.md' | xargs awesome_bot --allow-dupe --allow-redirect --skip-save-results

notifications:
  email: false
