site_name: CARLA Simulator
repo_url: https://github.com/carla-simulator/carla
docs_dir: Docs
edit_uri: 'edit/master/Docs/'
theme: readthedocs
extra_css: [extra.css]

nav:
- Home: 'index.md'
- Getting started: 
  - 'Introduction': 'getting_started/introduction.md'
  - 'Quickstart': 'getting_started/quickstart.md'
- Building CARLA:
  - 'Linux build': 'how_to_build_on_linux.md'
  - 'Windows build': 'how_to_build_on_windows.md'
  - "How to upgrade content": 'dev/how_to_upgrade_content.md'
  - 'Build system': 'dev/build_system.md'
  - 'Running in a Docker': 'carla_docker.md'
  - 'F.A.Q.': 'faq.md'
- Advanced configuration: 
  - 'Configuring the simulation': 'configuring_the_simulation.md'
  - 'Running without display and selecting GPUs': 'carla_headless.md'
- First steps: 
  - 'Python API tutorial': 'python_api_tutorial.md'
  - 'Python Cookbook': 'python_cookbook.md'
  - 'Cameras and sensors': 'cameras_and_sensors.md'
- General "How to...":
  - 'Add a new sensor': 'howto_general/how_to_add_a_new_sensor.md'
  - "Add friction triggers": "howto_general/how_to_add_friction_triggers.md"
  - "Control vehicle physics": "howto_general/how_to_control_vehicle_physics.md"
  - "Control walker skeletons": "howto_general/walker_bone_control.md"
  - "Create standalone asset packages for distribution": 'howto_general/asset_packages_for_dist.md'
  - 'Customize a map': 'howto_general/map_customization.md'
  - "Generate pedestrian navigation": 'howto_general/how_to_generate_pedestrians_navigation.md'
  - "Link Epic's Automotive Materials": 'howto_general/epic_automotive_materials.md'
  - "Record and replay": 'howto_general/recorder_and_playback.md'
  - "Recorder binary file format": 'howto_general/recorder_binary_file_format.md'
- Content "How to...":
  - 'Add assets': 'howto_content/how_to_add_assets.md'
  - "Create and import a new map": 'howto_content/how_to_make_a_new_map.md'
  - 'Model vehicles': 'howto_content/how_to_model_vehicles.md'
- References:
  - 'Python API reference': 'python_api.md'
  - 'Blueprint Library': 'bp_library.md'
  - 'C++ reference' : 'cpp_reference.md'
- Contributing:
  - 'Contribution guidelines': 'contributing/CONTRIBUTING.md'
  - "Make a release": 'contributing/how_to_make_a_release.md'
  - 'Coding standard': 'contributing/coding_standard.md'
  - 'Documentation standard': 'contributing/doc_standard.md'
  - 'Code of conduct': 'contributing/CODE_OF_CONDUCT.md'

markdown_extensions:
  - admonition
