[mypy]
python_version = 3.10
warn_return_any = True
warn_unused_configs = True
ignore_missing_imports = True
disallow_untyped_defs = False
strict_optional = True

[mypy-carla.*]
disallow_untyped_defs = True

[mypy-agents.*]
disallow_untyped_defs = True
