// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CarlaLaneInvasionEvent.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 3.3.2).
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "CarlaLaneInvasionEvent.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>


namespace carla_msgs {

namespace msg {

namespace CarlaLaneInvasionEvent_Constants {


} // namespace CarlaLaneInvasionEvent_Constants




CarlaLaneInvasionEvent::CarlaLaneInvasionEvent()
{
}

CarlaLaneInvasionEvent::~CarlaLaneInvasionEvent()
{
}

CarlaLaneInvasionEvent::CarlaLaneInvasionEvent(
        const CarlaLaneInvasionEvent& x)
{
    m_header = x.m_header;
    m_crossed_lane_markings = x.m_crossed_lane_markings;
}

CarlaLaneInvasionEvent::CarlaLaneInvasionEvent(
        CarlaLaneInvasionEvent&& x) noexcept
{
    m_header = std::move(x.m_header);
    m_crossed_lane_markings = std::move(x.m_crossed_lane_markings);
}

CarlaLaneInvasionEvent& CarlaLaneInvasionEvent::operator =(
        const CarlaLaneInvasionEvent& x)
{

    m_header = x.m_header;
    m_crossed_lane_markings = x.m_crossed_lane_markings;
    return *this;
}

CarlaLaneInvasionEvent& CarlaLaneInvasionEvent::operator =(
        CarlaLaneInvasionEvent&& x) noexcept
{

    m_header = std::move(x.m_header);
    m_crossed_lane_markings = std::move(x.m_crossed_lane_markings);
    return *this;
}

bool CarlaLaneInvasionEvent::operator ==(
        const CarlaLaneInvasionEvent& x) const
{
    return (m_header == x.m_header &&
           m_crossed_lane_markings == x.m_crossed_lane_markings);
}

bool CarlaLaneInvasionEvent::operator !=(
        const CarlaLaneInvasionEvent& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void CarlaLaneInvasionEvent::header(
        const std_msgs::msg::Header& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void CarlaLaneInvasionEvent::header(
        std_msgs::msg::Header&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const std_msgs::msg::Header& CarlaLaneInvasionEvent::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
std_msgs::msg::Header& CarlaLaneInvasionEvent::header()
{
    return m_header;
}


/*!
 * @brief This function copies the value in member crossed_lane_markings
 * @param _crossed_lane_markings New value to be copied in member crossed_lane_markings
 */
void CarlaLaneInvasionEvent::crossed_lane_markings(
        const std::vector<int32_t>& _crossed_lane_markings)
{
    m_crossed_lane_markings = _crossed_lane_markings;
}

/*!
 * @brief This function moves the value in member crossed_lane_markings
 * @param _crossed_lane_markings New value to be moved in member crossed_lane_markings
 */
void CarlaLaneInvasionEvent::crossed_lane_markings(
        std::vector<int32_t>&& _crossed_lane_markings)
{
    m_crossed_lane_markings = std::move(_crossed_lane_markings);
}

/*!
 * @brief This function returns a constant reference to member crossed_lane_markings
 * @return Constant reference to member crossed_lane_markings
 */
const std::vector<int32_t>& CarlaLaneInvasionEvent::crossed_lane_markings() const
{
    return m_crossed_lane_markings;
}

/*!
 * @brief This function returns a reference to member crossed_lane_markings
 * @return Reference to member crossed_lane_markings
 */
std::vector<int32_t>& CarlaLaneInvasionEvent::crossed_lane_markings()
{
    return m_crossed_lane_markings;
}




} // namespace msg


} // namespace carla_msgs
// Include auxiliary functions like for serializing/deserializing.
#include "CarlaLaneInvasionEventCdrAux.ipp"

