// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CarlaActorInfo.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 2.5.3).
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "CarlaActorInfo.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

#define carla_msgs_msg_CarlaActorInfo_max_cdr_typesize 53844ULL;
#define diagnostic_msgs_msg_KeyValue_max_cdr_typesize 520ULL;
#define carla_msgs_msg_CarlaActorInfo_max_key_cdr_typesize 0ULL;
#define diagnostic_msgs_msg_KeyValue_max_key_cdr_typesize 0ULL;
































carla_msgs::msg::CarlaActorInfo::CarlaActorInfo()
{
    // unsigned long long m_id
    m_id = 0;
    // unsigned long long m_parent_id
    m_parent_id = 0;
    // string m_type
    m_type ="";
    // string m_rosname
    m_rosname ="";
    // string m_rolename
    m_rolename ="";
    // string m_object_type
    m_object_type ="";
    // string m_base_type
    m_base_type ="";
    // string m_topic_prefix
    m_topic_prefix ="";
    // string m_frame_id
    m_frame_id ="";
    // uint8 m_city_object_label
    m_city_object_label = 0;
    // sequence<diagnostic_msgs::msg::KeyValue> m_attributes


}

carla_msgs::msg::CarlaActorInfo::~CarlaActorInfo()
{











}

carla_msgs::msg::CarlaActorInfo::CarlaActorInfo(
        const CarlaActorInfo& x)
{
    m_id = x.m_id;
    m_parent_id = x.m_parent_id;
    m_type = x.m_type;
    m_rosname = x.m_rosname;
    m_rolename = x.m_rolename;
    m_object_type = x.m_object_type;
    m_base_type = x.m_base_type;
    m_topic_prefix = x.m_topic_prefix;
    m_frame_id = x.m_frame_id;
    m_city_object_label = x.m_city_object_label;
    m_attributes = x.m_attributes;
}

carla_msgs::msg::CarlaActorInfo::CarlaActorInfo(
        CarlaActorInfo&& x) noexcept 
{
    m_id = x.m_id;
    m_parent_id = x.m_parent_id;
    m_type = std::move(x.m_type);
    m_rosname = std::move(x.m_rosname);
    m_rolename = std::move(x.m_rolename);
    m_object_type = std::move(x.m_object_type);
    m_base_type = std::move(x.m_base_type);
    m_topic_prefix = std::move(x.m_topic_prefix);
    m_frame_id = std::move(x.m_frame_id);
    m_city_object_label = x.m_city_object_label;
    m_attributes = std::move(x.m_attributes);
}

carla_msgs::msg::CarlaActorInfo& carla_msgs::msg::CarlaActorInfo::operator =(
        const CarlaActorInfo& x)
{

    m_id = x.m_id;
    m_parent_id = x.m_parent_id;
    m_type = x.m_type;
    m_rosname = x.m_rosname;
    m_rolename = x.m_rolename;
    m_object_type = x.m_object_type;
    m_base_type = x.m_base_type;
    m_topic_prefix = x.m_topic_prefix;
    m_frame_id = x.m_frame_id;
    m_city_object_label = x.m_city_object_label;
    m_attributes = x.m_attributes;

    return *this;
}

carla_msgs::msg::CarlaActorInfo& carla_msgs::msg::CarlaActorInfo::operator =(
        CarlaActorInfo&& x) noexcept
{

    m_id = x.m_id;
    m_parent_id = x.m_parent_id;
    m_type = std::move(x.m_type);
    m_rosname = std::move(x.m_rosname);
    m_rolename = std::move(x.m_rolename);
    m_object_type = std::move(x.m_object_type);
    m_base_type = std::move(x.m_base_type);
    m_topic_prefix = std::move(x.m_topic_prefix);
    m_frame_id = std::move(x.m_frame_id);
    m_city_object_label = x.m_city_object_label;
    m_attributes = std::move(x.m_attributes);

    return *this;
}

bool carla_msgs::msg::CarlaActorInfo::operator ==(
        const CarlaActorInfo& x) const
{

    return (m_id == x.m_id && m_parent_id == x.m_parent_id && m_type == x.m_type && m_rosname == x.m_rosname && m_rolename == x.m_rolename && m_object_type == x.m_object_type && m_base_type == x.m_base_type && m_topic_prefix == x.m_topic_prefix && m_frame_id == x.m_frame_id && m_city_object_label == x.m_city_object_label && m_attributes == x.m_attributes);
}

bool carla_msgs::msg::CarlaActorInfo::operator !=(
        const CarlaActorInfo& x) const
{
    return !(*this == x);
}

size_t carla_msgs::msg::CarlaActorInfo::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return carla_msgs_msg_CarlaActorInfo_max_cdr_typesize;
}

size_t carla_msgs::msg::CarlaActorInfo::getCdrSerializedSize(
        const carla_msgs::msg::CarlaActorInfo& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.type().size() + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.rosname().size() + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.rolename().size() + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.object_type().size() + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.base_type().size() + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.topic_prefix().size() + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.frame_id().size() + 1;

    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    for(size_t a = 0; a < data.attributes().size(); ++a)
    {
        current_alignment += diagnostic_msgs::msg::KeyValue::getCdrSerializedSize(data.attributes().at(a), current_alignment);}


    return current_alignment - initial_alignment;
}

void carla_msgs::msg::CarlaActorInfo::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_id;
    scdr << m_parent_id;
    scdr << m_type.c_str();
    scdr << m_rosname.c_str();
    scdr << m_rolename.c_str();
    scdr << m_object_type.c_str();
    scdr << m_base_type.c_str();
    scdr << m_topic_prefix.c_str();
    scdr << m_frame_id.c_str();
    scdr << m_city_object_label;
    scdr << m_attributes;

}

void carla_msgs::msg::CarlaActorInfo::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_id;
    dcdr >> m_parent_id;
    dcdr >> m_type;
    dcdr >> m_rosname;
    dcdr >> m_rolename;
    dcdr >> m_object_type;
    dcdr >> m_base_type;
    dcdr >> m_topic_prefix;
    dcdr >> m_frame_id;
    dcdr >> m_city_object_label;
    dcdr >> m_attributes;
}

/*!
 * @brief This function sets a value in member id
 * @param _id New value for member id
 */
void carla_msgs::msg::CarlaActorInfo::id(
        uint64_t _id)
{
    m_id = _id;
}

/*!
 * @brief This function returns the value of member id
 * @return Value of member id
 */
uint64_t carla_msgs::msg::CarlaActorInfo::id() const
{
    return m_id;
}

/*!
 * @brief This function returns a reference to member id
 * @return Reference to member id
 */
uint64_t& carla_msgs::msg::CarlaActorInfo::id()
{
    return m_id;
}

/*!
 * @brief This function sets a value in member parent_id
 * @param _parent_id New value for member parent_id
 */
void carla_msgs::msg::CarlaActorInfo::parent_id(
        uint64_t _parent_id)
{
    m_parent_id = _parent_id;
}

/*!
 * @brief This function returns the value of member parent_id
 * @return Value of member parent_id
 */
uint64_t carla_msgs::msg::CarlaActorInfo::parent_id() const
{
    return m_parent_id;
}

/*!
 * @brief This function returns a reference to member parent_id
 * @return Reference to member parent_id
 */
uint64_t& carla_msgs::msg::CarlaActorInfo::parent_id()
{
    return m_parent_id;
}

/*!
 * @brief This function copies the value in member type
 * @param _type New value to be copied in member type
 */
void carla_msgs::msg::CarlaActorInfo::type(
        const std::string& _type)
{
    m_type = _type;
}

/*!
 * @brief This function moves the value in member type
 * @param _type New value to be moved in member type
 */
void carla_msgs::msg::CarlaActorInfo::type(
        std::string&& _type)
{
    m_type = std::move(_type);
}

/*!
 * @brief This function returns a constant reference to member type
 * @return Constant reference to member type
 */
const std::string& carla_msgs::msg::CarlaActorInfo::type() const
{
    return m_type;
}

/*!
 * @brief This function returns a reference to member type
 * @return Reference to member type
 */
std::string& carla_msgs::msg::CarlaActorInfo::type()
{
    return m_type;
}
/*!
 * @brief This function copies the value in member rosname
 * @param _rosname New value to be copied in member rosname
 */
void carla_msgs::msg::CarlaActorInfo::rosname(
        const std::string& _rosname)
{
    m_rosname = _rosname;
}

/*!
 * @brief This function moves the value in member rosname
 * @param _rosname New value to be moved in member rosname
 */
void carla_msgs::msg::CarlaActorInfo::rosname(
        std::string&& _rosname)
{
    m_rosname = std::move(_rosname);
}

/*!
 * @brief This function returns a constant reference to member rosname
 * @return Constant reference to member rosname
 */
const std::string& carla_msgs::msg::CarlaActorInfo::rosname() const
{
    return m_rosname;
}

/*!
 * @brief This function returns a reference to member rosname
 * @return Reference to member rosname
 */
std::string& carla_msgs::msg::CarlaActorInfo::rosname()
{
    return m_rosname;
}
/*!
 * @brief This function copies the value in member rolename
 * @param _rolename New value to be copied in member rolename
 */
void carla_msgs::msg::CarlaActorInfo::rolename(
        const std::string& _rolename)
{
    m_rolename = _rolename;
}

/*!
 * @brief This function moves the value in member rolename
 * @param _rolename New value to be moved in member rolename
 */
void carla_msgs::msg::CarlaActorInfo::rolename(
        std::string&& _rolename)
{
    m_rolename = std::move(_rolename);
}

/*!
 * @brief This function returns a constant reference to member rolename
 * @return Constant reference to member rolename
 */
const std::string& carla_msgs::msg::CarlaActorInfo::rolename() const
{
    return m_rolename;
}

/*!
 * @brief This function returns a reference to member rolename
 * @return Reference to member rolename
 */
std::string& carla_msgs::msg::CarlaActorInfo::rolename()
{
    return m_rolename;
}
/*!
 * @brief This function copies the value in member object_type
 * @param _object_type New value to be copied in member object_type
 */
void carla_msgs::msg::CarlaActorInfo::object_type(
        const std::string& _object_type)
{
    m_object_type = _object_type;
}

/*!
 * @brief This function moves the value in member object_type
 * @param _object_type New value to be moved in member object_type
 */
void carla_msgs::msg::CarlaActorInfo::object_type(
        std::string&& _object_type)
{
    m_object_type = std::move(_object_type);
}

/*!
 * @brief This function returns a constant reference to member object_type
 * @return Constant reference to member object_type
 */
const std::string& carla_msgs::msg::CarlaActorInfo::object_type() const
{
    return m_object_type;
}

/*!
 * @brief This function returns a reference to member object_type
 * @return Reference to member object_type
 */
std::string& carla_msgs::msg::CarlaActorInfo::object_type()
{
    return m_object_type;
}
/*!
 * @brief This function copies the value in member base_type
 * @param _base_type New value to be copied in member base_type
 */
void carla_msgs::msg::CarlaActorInfo::base_type(
        const std::string& _base_type)
{
    m_base_type = _base_type;
}

/*!
 * @brief This function moves the value in member base_type
 * @param _base_type New value to be moved in member base_type
 */
void carla_msgs::msg::CarlaActorInfo::base_type(
        std::string&& _base_type)
{
    m_base_type = std::move(_base_type);
}

/*!
 * @brief This function returns a constant reference to member base_type
 * @return Constant reference to member base_type
 */
const std::string& carla_msgs::msg::CarlaActorInfo::base_type() const
{
    return m_base_type;
}

/*!
 * @brief This function returns a reference to member base_type
 * @return Reference to member base_type
 */
std::string& carla_msgs::msg::CarlaActorInfo::base_type()
{
    return m_base_type;
}
/*!
 * @brief This function copies the value in member topic_prefix
 * @param _topic_prefix New value to be copied in member topic_prefix
 */
void carla_msgs::msg::CarlaActorInfo::topic_prefix(
        const std::string& _topic_prefix)
{
    m_topic_prefix = _topic_prefix;
}

/*!
 * @brief This function moves the value in member topic_prefix
 * @param _topic_prefix New value to be moved in member topic_prefix
 */
void carla_msgs::msg::CarlaActorInfo::topic_prefix(
        std::string&& _topic_prefix)
{
    m_topic_prefix = std::move(_topic_prefix);
}

/*!
 * @brief This function returns a constant reference to member topic_prefix
 * @return Constant reference to member topic_prefix
 */
const std::string& carla_msgs::msg::CarlaActorInfo::topic_prefix() const
{
    return m_topic_prefix;
}

/*!
 * @brief This function returns a reference to member topic_prefix
 * @return Reference to member topic_prefix
 */
std::string& carla_msgs::msg::CarlaActorInfo::topic_prefix()
{
    return m_topic_prefix;
}
/*!
 * @brief This function copies the value in member frame_id
 * @param _frame_id New value to be copied in member frame_id
 */
void carla_msgs::msg::CarlaActorInfo::frame_id(
        const std::string& _frame_id)
{
    m_frame_id = _frame_id;
}

/*!
 * @brief This function moves the value in member frame_id
 * @param _frame_id New value to be moved in member frame_id
 */
void carla_msgs::msg::CarlaActorInfo::frame_id(
        std::string&& _frame_id)
{
    m_frame_id = std::move(_frame_id);
}

/*!
 * @brief This function returns a constant reference to member frame_id
 * @return Constant reference to member frame_id
 */
const std::string& carla_msgs::msg::CarlaActorInfo::frame_id() const
{
    return m_frame_id;
}

/*!
 * @brief This function returns a reference to member frame_id
 * @return Reference to member frame_id
 */
std::string& carla_msgs::msg::CarlaActorInfo::frame_id()
{
    return m_frame_id;
}
/*!
 * @brief This function sets a value in member city_object_label
 * @param _city_object_label New value for member city_object_label
 */
void carla_msgs::msg::CarlaActorInfo::city_object_label(
        uint8_t _city_object_label)
{
    m_city_object_label = _city_object_label;
}

/*!
 * @brief This function returns the value of member city_object_label
 * @return Value of member city_object_label
 */
uint8_t carla_msgs::msg::CarlaActorInfo::city_object_label() const
{
    return m_city_object_label;
}

/*!
 * @brief This function returns a reference to member city_object_label
 * @return Reference to member city_object_label
 */
uint8_t& carla_msgs::msg::CarlaActorInfo::city_object_label()
{
    return m_city_object_label;
}

/*!
 * @brief This function copies the value in member attributes
 * @param _attributes New value to be copied in member attributes
 */
void carla_msgs::msg::CarlaActorInfo::attributes(
        const std::vector<diagnostic_msgs::msg::KeyValue>& _attributes)
{
    m_attributes = _attributes;
}

/*!
 * @brief This function moves the value in member attributes
 * @param _attributes New value to be moved in member attributes
 */
void carla_msgs::msg::CarlaActorInfo::attributes(
        std::vector<diagnostic_msgs::msg::KeyValue>&& _attributes)
{
    m_attributes = std::move(_attributes);
}

/*!
 * @brief This function returns a constant reference to member attributes
 * @return Constant reference to member attributes
 */
const std::vector<diagnostic_msgs::msg::KeyValue>& carla_msgs::msg::CarlaActorInfo::attributes() const
{
    return m_attributes;
}

/*!
 * @brief This function returns a reference to member attributes
 * @return Reference to member attributes
 */
std::vector<diagnostic_msgs::msg::KeyValue>& carla_msgs::msg::CarlaActorInfo::attributes()
{
    return m_attributes;
}


size_t carla_msgs::msg::CarlaActorInfo::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return carla_msgs_msg_CarlaActorInfo_max_key_cdr_typesize;
}

bool carla_msgs::msg::CarlaActorInfo::isKeyDefined()
{
    return false;
}

void carla_msgs::msg::CarlaActorInfo::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}



