// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CarlaSynchronizationWindow.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 3.3.2).
 */

#ifndef _FAST_DDS_GENERATED_CARLA_MSGS_MSG_CARLASYNCHRONIZATIONWINDOW_H_
#define _FAST_DDS_GENERATED_CARLA_MSGS_MSG_CARLASYNCHRONIZATIONWINDOW_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(CARLASYNCHRONIZATIONWINDOW_SOURCE)
#define CARLASYNCHRONIZATIONWINDOW_DllAPI __declspec( dllexport )
#else
#define CARLASYNCHRONIZATIONWINDOW_DllAPI __declspec( dllimport )
#endif // CARLASYNCHRONIZATIONWINDOW_SOURCE
#else
#define CARLASYNCHRONIZATIONWINDOW_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define CARLASYNCHRONIZATIONWINDOW_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace carla_msgs {

namespace msg {



/*!
 * @brief This class represents the structure CarlaSynchronizationWindow defined by the user in the IDL file.
 * @ingroup CarlaSynchronizationWindow
 */
class CarlaSynchronizationWindow
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CarlaSynchronizationWindow();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CarlaSynchronizationWindow();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object carla_msgs::msg::CarlaSynchronizationWindow that will be copied.
     */
    eProsima_user_DllExport CarlaSynchronizationWindow(
            const CarlaSynchronizationWindow& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object carla_msgs::msg::CarlaSynchronizationWindow that will be copied.
     */
    eProsima_user_DllExport CarlaSynchronizationWindow(
            CarlaSynchronizationWindow&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object carla_msgs::msg::CarlaSynchronizationWindow that will be copied.
     */
    eProsima_user_DllExport CarlaSynchronizationWindow& operator =(
            const CarlaSynchronizationWindow& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object carla_msgs::msg::CarlaSynchronizationWindow that will be copied.
     */
    eProsima_user_DllExport CarlaSynchronizationWindow& operator =(
            CarlaSynchronizationWindow&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x carla_msgs::msg::CarlaSynchronizationWindow object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CarlaSynchronizationWindow& x) const;

    /*!
     * @brief Comparison operator.
     * @param x carla_msgs::msg::CarlaSynchronizationWindow object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CarlaSynchronizationWindow& x) const;

    /*!
     * @brief This function sets a value in member synchronization_window_target_game_time
     * @param _synchronization_window_target_game_time New value for member synchronization_window_target_game_time
     */
    eProsima_user_DllExport void synchronization_window_target_game_time(
            float _synchronization_window_target_game_time);

    /*!
     * @brief This function returns the value of member synchronization_window_target_game_time
     * @return Value of member synchronization_window_target_game_time
     */
    eProsima_user_DllExport float synchronization_window_target_game_time() const;

    /*!
     * @brief This function returns a reference to member synchronization_window_target_game_time
     * @return Reference to member synchronization_window_target_game_time
     */
    eProsima_user_DllExport float& synchronization_window_target_game_time();

private:

    float m_synchronization_window_target_game_time{0.0};

};

} // namespace msg

} // namespace carla_msgs

#endif // _FAST_DDS_GENERATED_CARLA_MSGS_MSG_CARLASYNCHRONIZATIONWINDOW_H_



