<?xml version="1.0"?>
<package format="3">
  <name>carla_msgs</name>
  <version>0.0.1</version>
  <description>CARLA custom ROS2 message types</description>
  <maintainer email="carla@carla.org">carla</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>

  <member_of_group>rosidl_interface_packages</member_of_group>
</package>
