#!/usr/bin/env python

# Copyright (c) 2019 Computer Vision Center (CVC) at the Universitat Autonoma de
# Barcelona (UAB).
#
# This work is licensed under the terms of the MIT license.
# For a copy, see <https://opensource.org/licenses/MIT>.

import glob
import os
import sys

try:
    sys.path.append(glob.glob('../carla/dist/carla-*%d.%d-%s.egg' % (
        sys.version_info.major,
        sys.version_info.minor,
        'win-amd64' if os.name == 'nt' else 'linux-x86_64'))[0])
except IndexError:
    pass

import carla

import random
import time



def SaveFinalColorTexture(image):
    image.save_to_disk('_out/FinalColor-%06d.png' % image.frame)

def SaveSceneColorTexture(image):
    image.save_to_disk('_out/SceneColor-%06d.png' % image.frame)

def SaveSceneDepthTexture(image):
    image.save_to_disk('_out/SceneDepth-%06d.png' % image.frame)

def SaveSceneStencilTexture(image):
    image.save_to_disk('_out/SceneStencil-%06d.png' % image.frame)

def SaveGBufferATexture(image):
    image.save_to_disk('_out/GBufferA-%06d.png' % image.frame)

def SaveGBufferBTexture(image):
    image.save_to_disk('_out/GBufferB-%06d.png' % image.frame)

def SaveGBufferCTexture(image):
    image.save_to_disk('_out/GBufferC-%06d.png' % image.frame)

def SaveGBufferDTexture(image):
    image.save_to_disk('_out/GBufferD-%06d.png' % image.frame)

def SaveGBufferETexture(image):
    image.save_to_disk('_out/GBufferE-%06d.png' % image.frame)

def SaveGBufferFTexture(image):
    image.save_to_disk('_out/GBufferF-%06d.png' % image.frame)

def SaveVelocityTexture(image):
    image.save_to_disk('_out/Velocity-%06d.png' % image.frame)

def SaveSSAOTexture(image):
    image.save_to_disk('_out/SSAO-%06d.png' % image.frame)

def SaveCustomDepthTexture(image):
    image.save_to_disk('_out/CustomDepth-%06d.png' % image.frame)

def SaveCustomStencilTexture(image):
    image.save_to_disk('_out/CustomStencil-%06d.png' % image.frame)



def main():
    actor_list = []

    # In this tutorial script, we are going to add a vehicle to the simulation
    # and let it drive in autopilot. We will also create a camera attached to
    # that vehicle, and save all the images generated by the camera to disk.

    try:
        # First of all, we need to create the client that will send the requests
        # to the simulator. Here we'll assume the simulator is accepting
        # requests in the localhost at port 2000.
        client = carla.Client('127.0.0.1', 2000)
        client.set_timeout(2.0)

        # Once we have a client we can retrieve the world that is currently
        # running.
        world = client.get_world()

        # The world contains the list blueprints that we can use for adding new
        # actors into the simulation.
        blueprint_library = world.get_blueprint_library()

        # Now let's filter all the blueprints of type 'vehicle' and choose one
        # at random.
        bp = random.choice(blueprint_library.filter('vehicle'))

        # A blueprint contains the list of attributes that define a vehicle's
        # instance, we can read them and modify some of them. For instance,
        # let's randomize its color.
        if bp.has_attribute('color'):
            color = random.choice(bp.get_attribute('color').recommended_values)
            bp.set_attribute('color', color)

        # Now we need to give an initial transform to the vehicle. We choose a
        # random transform from the list of recommended spawn points of the map.
        transform = world.get_map().get_spawn_points()[0]

        # So let's tell the world to spawn the vehicle.
        vehicle = world.spawn_actor(bp, transform)

        # It is important to note that the actors we create won't be destroyed
        # unless we call their "destroy" function. If we fail to call "destroy"
        # they will stay in the simulation even after we quit the Python script.
        # For that reason, we are storing all the actors we create so we can
        # destroy them afterwards.
        actor_list.append(vehicle)
        print('created %s' % vehicle.type_id)

        # Let's put the vehicle to drive around.
        vehicle.set_autopilot(True)

        width = 1920
        height = 1080

        # Let's add now a "depth" camera attached to the vehicle. Note that the
        # transform we give here is now relative to the vehicle.
        camera_bp = blueprint_library.find('sensor.camera.rgb')
        camera_bp.set_attribute('image_size_x', str(width))
        camera_bp.set_attribute('image_size_y', str(height))
        camera_transform = carla.Transform(carla.Location(x=1.5, z=2.4))
        camera = world.spawn_actor(camera_bp, camera_transform, attach_to=vehicle)
        actor_list.append(camera)
        print('created %s' % camera.type_id)

        # Regular image capture, this is currently mandatory for the GBuffers to be extracted:
        camera.listen(SaveFinalColorTexture)
        # GBuffer image capture:
        camera.listen_to_gbuffer(0, SaveSceneColorTexture)
        camera.listen_to_gbuffer(1, SaveSceneDepthTexture)
        camera.listen_to_gbuffer(2, SaveSceneStencilTexture)
        camera.listen_to_gbuffer(3, SaveGBufferATexture)
        camera.listen_to_gbuffer(4, SaveGBufferBTexture)
        camera.listen_to_gbuffer(5, SaveGBufferCTexture)
        camera.listen_to_gbuffer(6, SaveGBufferDTexture)
        camera.listen_to_gbuffer(7, SaveGBufferETexture)
        camera.listen_to_gbuffer(8, SaveGBufferFTexture)
        camera.listen_to_gbuffer(9, SaveVelocityTexture)
        camera.listen_to_gbuffer(10, SaveSSAOTexture)
        camera.listen_to_gbuffer(11, SaveCustomDepthTexture)
        camera.listen_to_gbuffer(12, SaveCustomStencilTexture)
        time.sleep(10)

    finally:

        print('destroying actors')
        camera.destroy()
        client.apply_batch([carla.command.DestroyActor(x) for x in actor_list])
        print('done.')


if __name__ == '__main__':

    main()
