/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /workspaces/carla/LibCarla/source/carla/ros2/types/cyclonedds/tf2_msgs/TF2Error.h
  Source: /workspaces/carla/LibCarla/source/carla/ros2/types/idl/tf2_msgs/TF2Error.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__WORKSPACES_CARLA_LIBCARLA_SOURCE_CARLA_ROS2_TYPES_CYCLONEDDS_TF2_MSGS_TF2ERROR_H
#define DDSC__WORKSPACES_CARLA_LIBCARLA_SOURCE_CARLA_ROS2_TYPES_CYCLONEDDS_TF2_MSGS_TF2ERROR_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct tf2_msgs_msg_TF2Error
{
  uint8_t error;
  char * error_string;
} tf2_msgs_msg_TF2Error;

extern const dds_topic_descriptor_t tf2_msgs_msg_TF2Error_desc;

#define tf2_msgs_msg_TF2Error__alloc() \
((tf2_msgs_msg_TF2Error*) dds_alloc (sizeof (tf2_msgs_msg_TF2Error)));

#define tf2_msgs_msg_TF2Error_free(d,o) \
dds_sample_free ((d), &tf2_msgs_msg_TF2Error_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__WORKSPACES_CARLA_LIBCARLA_SOURCE_CARLA_ROS2_TYPES_CYCLONEDDS_TF2_MSGS_TF2ERROR_H */
