// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Odometry.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 3.3.2).
 */

#ifndef _FAST_DDS_GENERATED_NAV_MSGS_MSG_ODOMETRY_H_
#define _FAST_DDS_GENERATED_NAV_MSGS_MSG_ODOMETRY_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>

#include "geometry_msgs/msg/PoseWithCovariance.h"
#include "geometry_msgs/msg/TwistWithCovariance.h"
#include "std_msgs/msg/Header.h"


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(ODOMETRY_SOURCE)
#define ODOMETRY_DllAPI __declspec( dllexport )
#else
#define ODOMETRY_DllAPI __declspec( dllimport )
#endif // ODOMETRY_SOURCE
#else
#define ODOMETRY_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define ODOMETRY_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace nav_msgs {

namespace msg {



/*!
 * @brief This class represents the structure Odometry defined by the user in the IDL file.
 * @ingroup Odometry
 */
class Odometry
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Odometry();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Odometry();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object nav_msgs::msg::Odometry that will be copied.
     */
    eProsima_user_DllExport Odometry(
            const Odometry& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object nav_msgs::msg::Odometry that will be copied.
     */
    eProsima_user_DllExport Odometry(
            Odometry&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object nav_msgs::msg::Odometry that will be copied.
     */
    eProsima_user_DllExport Odometry& operator =(
            const Odometry& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object nav_msgs::msg::Odometry that will be copied.
     */
    eProsima_user_DllExport Odometry& operator =(
            Odometry&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x nav_msgs::msg::Odometry object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Odometry& x) const;

    /*!
     * @brief Comparison operator.
     * @param x nav_msgs::msg::Odometry object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Odometry& x) const;

    /*!
     * @brief This function copies the value in member header
     * @param _header New value to be copied in member header
     */
    eProsima_user_DllExport void header(
            const std_msgs::msg::Header& _header);

    /*!
     * @brief This function moves the value in member header
     * @param _header New value to be moved in member header
     */
    eProsima_user_DllExport void header(
            std_msgs::msg::Header&& _header);

    /*!
     * @brief This function returns a constant reference to member header
     * @return Constant reference to member header
     */
    eProsima_user_DllExport const std_msgs::msg::Header& header() const;

    /*!
     * @brief This function returns a reference to member header
     * @return Reference to member header
     */
    eProsima_user_DllExport std_msgs::msg::Header& header();


    /*!
     * @brief This function copies the value in member child_frame_id
     * @param _child_frame_id New value to be copied in member child_frame_id
     */
    eProsima_user_DllExport void child_frame_id(
            const std::string& _child_frame_id);

    /*!
     * @brief This function moves the value in member child_frame_id
     * @param _child_frame_id New value to be moved in member child_frame_id
     */
    eProsima_user_DllExport void child_frame_id(
            std::string&& _child_frame_id);

    /*!
     * @brief This function returns a constant reference to member child_frame_id
     * @return Constant reference to member child_frame_id
     */
    eProsima_user_DllExport const std::string& child_frame_id() const;

    /*!
     * @brief This function returns a reference to member child_frame_id
     * @return Reference to member child_frame_id
     */
    eProsima_user_DllExport std::string& child_frame_id();


    /*!
     * @brief This function copies the value in member pose
     * @param _pose New value to be copied in member pose
     */
    eProsima_user_DllExport void pose(
            const geometry_msgs::msg::PoseWithCovariance& _pose);

    /*!
     * @brief This function moves the value in member pose
     * @param _pose New value to be moved in member pose
     */
    eProsima_user_DllExport void pose(
            geometry_msgs::msg::PoseWithCovariance&& _pose);

    /*!
     * @brief This function returns a constant reference to member pose
     * @return Constant reference to member pose
     */
    eProsima_user_DllExport const geometry_msgs::msg::PoseWithCovariance& pose() const;

    /*!
     * @brief This function returns a reference to member pose
     * @return Reference to member pose
     */
    eProsima_user_DllExport geometry_msgs::msg::PoseWithCovariance& pose();


    /*!
     * @brief This function copies the value in member twist
     * @param _twist New value to be copied in member twist
     */
    eProsima_user_DllExport void twist(
            const geometry_msgs::msg::TwistWithCovariance& _twist);

    /*!
     * @brief This function moves the value in member twist
     * @param _twist New value to be moved in member twist
     */
    eProsima_user_DllExport void twist(
            geometry_msgs::msg::TwistWithCovariance&& _twist);

    /*!
     * @brief This function returns a constant reference to member twist
     * @return Constant reference to member twist
     */
    eProsima_user_DllExport const geometry_msgs::msg::TwistWithCovariance& twist() const;

    /*!
     * @brief This function returns a reference to member twist
     * @return Reference to member twist
     */
    eProsima_user_DllExport geometry_msgs::msg::TwistWithCovariance& twist();

private:

    std_msgs::msg::Header m_header;
    std::string m_child_frame_id;
    geometry_msgs::msg::PoseWithCovariance m_pose;
    geometry_msgs::msg::TwistWithCovariance m_twist;

};

} // namespace msg

} // namespace nav_msgs

#endif // _FAST_DDS_GENERATED_NAV_MSGS_MSG_ODOMETRY_H_



