#! /bin/bash

# ==============================================================================
# -- Parse arguments -----------------------------------------------------------
# ==============================================================================

DOC_STRING="Download and install the required libraries for carla."

USAGE_STRING="Usage: $0 [--python-version=VERSION]"

OPTS=`getopt -o h --long help,chrono,chrono-path:,ros2,pytorch,python-version: -n 'parse-options' -- "$@"`

eval set -- "$OPTS"

PY_VERSION_LIST=3
USE_CHRONO=false
USE_PYTORCH=false
USE_ROS2=false
CHRONO_PATH=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --python-version )
      PY_VERSION_LIST="$2";
      shift 2 ;;
    --chrono )
      USE_CHRONO=true;
      shift ;;
    --chrono-path )
      CHRONO_PATH="$2";
      USE_CHRONO=true;
      shift 2 ;;
    --pytorch )
      USE_PYTORCH=true;
      shift ;;
    --ros2 )
      USE_ROS2=true;
      shift ;;
    -h | --help )
      echo "$DOC_STRING"
      echo "$USAGE_STRING"
      exit 1
      ;;
    * )
      shift ;;
  esac
done

# ==============================================================================
# -- Set up environment --------------------------------------------------------
# ==============================================================================

source $(dirname "$0")/Environment.sh

# Convert comma-separated string to array of unique elements.
IFS="," read -r -a PY_VERSION_LIST <<< "${PY_VERSION_LIST}"

mkdir -p ${CARLA_BUILD_FOLDER}
pushd ${CARLA_BUILD_FOLDER} >/dev/null

# ==============================================================================
# -- Setup Unreal Engine toolchain flags ---------------------------------------
# ==============================================================================
LLVM_INCLUDE="${UE4_ROOT}/Engine/Source/ThirdParty/Linux/LibCxx/include/c++/v1"
LLVM_LIBPATH="${UE4_ROOT}/Engine/Source/ThirdParty/Linux/LibCxx/lib/Linux/x86_64-unknown-linux-gnu"
UNREAL_SYSROOT="$UE4_ROOT/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v17_clang-10.0.1-centos7/x86_64-unknown-linux-gnu"
UNREAL_HOSTED_CFLAGS="--sysroot=${UNREAL_SYSROOT} -isystem ${LLVM_INCLUDE}"
UNREAL_SYSTEM_LIBPATH="${UNREAL_SYSROOT}/usr/lib"
UNREAL_HOSTED_LINKER_FLAGS="--sysroot=${UNREAL_SYSROOT} -L${LLVM_LIBPATH} -L${UNREAL_SYSTEM_LIBPATH} -lc++ -lc++abi"

CARLA_CFLAGS="-fPIC -w"
CARLA_CXXFLAGS="-std=c++17 -DBOOST_ERROR_CODE_HEADER_ONLY"

CARLA_SERVER_CFLAGS="${UNREAL_HOSTED_CFLAGS} ${CARLA_CFLAGS}"
CARLA_SERVER_CXXFLAGS="${CARLA_SERVER_CFLAGS} ${CARLA_CXXFLAGS} -stdlib=libc++ -DBOOST_NO_EXCEPTIONS -DASIO_NO_EXCEPTIONS"
CARLA_SERVER_LINKER_FLAGS="${UNREAL_HOSTED_LINKER_FLAGS} -L${LIBCARLA_INSTALL_SERVER_FOLDER}/lib/"

CARLA_SERVER_CC="${UNREAL_SYSROOT}/bin/clang"
CARLA_SERVER_CXX="${UNREAL_SYSROOT}/bin/clang++"
CARLA_CLIENT_CCC="gcc"
CARLA_CLIENT_CXX="g++"

CLANG_ONLY_WARNINGS="-Wduplicate-enum -Wheader-hygiene -Wfloat-overflow-conversion"


# ==============================================================================
# -- Generate CMake toolchains -------------------------------------------------
# ==============================================================================

log "Generating CMake configuration files."

# -- CARLA_CLIENT_TOOLCHAIN_FILE --------------------------------------------------

cat >${CARLA_CLIENT_TOOLCHAIN_FILE}.gen <<EOL
# Automatically generated by `basename "$0"`

set(CMAKE_C_COMPILER ${CARLA_CLIENT_CCC})
set(CMAKE_CXX_COMPILER ${CARLA_CLIENT_CXX})

# disable -Werror since the boost 1.72 doesn't compile with ad_rss without warnings (i.e. the geometry headers)
set(CMAKE_C_FLAGS "\${CMAKE_C_FLAGS} ${CARLA_CFLAGS}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "\${CMAKE_CXX_FLAGS} ${CARLA_CFLAGS} ${CARLA_CXXFLAGS} -pthread" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "\${CMAKE_CXX_FLAGS} -Wall -Wextra -Wpedantic" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "\${CMAKE_CXX_FLAGS} -Wdeprecated -Wshadow -Wuninitialized -Wunreachable-code" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "\${CMAKE_CXX_FLAGS} -Wpessimizing-move -Wold-style-cast -Wnull-dereference" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "\${CMAKE_CXX_FLAGS} -Wnon-virtual-dtor" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "\${CMAKE_CXX_FLAGS} -Wconversion" CACHE STRING "" FORCE)

# @todo These flags need to be compatible with setup.py compilation.
set(CMAKE_C_FLAGS_RELEASE_CLIENT "-Wstrict-prototypes")
set(CMAKE_CXX_FLAGS_RELEASE_CLIENT "\${CMAKE_CXX_FLAGS_RELEASE} -DNDEBUG -g -fwrapv -O2 -Wall -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c++17 -Wno-missing-braces -DBOOST_ERROR_CODE_HEADER_ONLY" CACHE STRING "" FORCE)
EOL

# -- CARLA_SERVER_TOOLCHAIN_FILE -----------------------------------------------------

# We can reuse the previous toolchain.
cp ${CARLA_CLIENT_TOOLCHAIN_FILE}.gen ${CARLA_SERVER_TOOLCHAIN_FILE}.gen

cat >>${CARLA_SERVER_TOOLCHAIN_FILE}.gen <<EOL

set(CMAKE_C_COMPILER ${CARLA_SERVER_CC})
set(CMAKE_CXX_COMPILER ${CARLA_SERVER_CXX})

set(BUILD_STATIC_LIBS ON)
set(BUILD_SHARED_LIBS OFF)
set(CMAKE_CXX_FLAGS "\${CMAKE_CXX_FLAGS} ${CARLA_SERVER_CXXFLAGS} ${CLANG_ONLY_WARNINGS}" CACHE STRING "" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS "\${CMAKE_SHARED_LINKER_FLAGS} ${CARLA_SERVER_LINKER_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS "\${CMAKE_EXE_LINKER_FLAGS} ${CARLA_SERVER_LINKER_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_RPATH "\$ORIGIN/../../CarlaDependencies/lib")
set(CMAKE_BUILD_RPATH_USE_ORIGIN True)
EOL

# -- Move files ----------------------------------------------------------------

move_if_changed "${CARLA_CLIENT_TOOLCHAIN_FILE}.gen" "${CARLA_CLIENT_TOOLCHAIN_FILE}"
move_if_changed "${CARLA_SERVER_TOOLCHAIN_FILE}.gen" "${CARLA_SERVER_TOOLCHAIN_FILE}"

# ==============================================================================
# -- Get boost includes --------------------------------------------------------
# ==============================================================================

BOOST_VERSION=1.84.0
BOOST_BASENAME="boost-${BOOST_VERSION}"
BOOST_SHA256SUM="a5800f405508f5df8114558ca9855d2640a2de8f0445f051fa1c7c3383045724"
BOOST_PACKAGE_BASENAME=boost_${BOOST_VERSION//./_}

BOOST_CLIENT_INCLUDE=${PWD}/${BOOST_BASENAME}-client-install/include
BOOST_CLIENT_LIBPATH=${PWD}/${BOOST_BASENAME}-client-install/lib
BOOST_SERVER_INCLUDE=${PWD}/${BOOST_BASENAME}-server-install/include
BOOST_SERVER_LIBPATH=${PWD}/${BOOST_BASENAME}-server-install/lib

for PY_VERSION in ${PY_VERSION_LIST[@]} ; do
  SHOULD_BUILD_BOOST_CLIENT=true
  SHOULD_BUILD_BOOST_SERVER=true
  PYTHON_VERSION=$(/usr/bin/env python${PY_VERSION} -V 2>&1)
  LIB_NAME=$(cut -d . -f 1,2 <<< "$PYTHON_VERSION" | tr -d .)
  LIB_NAME=${LIB_NAME:7}
  if [[ -d "${BOOST_BASENAME}-client-install" ]] ; then
    if [ -f "${BOOST_BASENAME}-client-install/lib/libboost_python${LIB_NAME}.a" ] ; then
      SHOULD_BUILD_BOOST_CLIENT=false
      log "${BOOST_BASENAME} already installed for Python ${PY_VERSION}."
    fi
  fi
  if [[ -d "${BOOST_BASENAME}-server-install" ]] ; then
    if [ -f "${BOOST_BASENAME}-server-install/lib/libboost_system.a" ] ; then
      SHOULD_BUILD_BOOST_SERVER=false
    fi
  fi

  if { ${SHOULD_BUILD_BOOST_SERVER} -o ${SHOULD_BUILD_BOOST_CLIENT}; } ; then
    # Download boost if required
    if [ ! -f "${BOOST_PACKAGE_BASENAME}.tar.gz" ]; then
      log "Retrieving boost."

      start=$(date +%s)
      wget "https://archives.boost.io/release/${BOOST_VERSION}/source/${BOOST_PACKAGE_BASENAME}.tar.gz" -O ${BOOST_PACKAGE_BASENAME}.tar.gz || true
      end=$(date +%s)
      echo "Elapsed Time downloading from boost webpage: $(($end-$start)) seconds"

      # try to use the backup boost we have in Jenkins
      if [ ! -f "${BOOST_PACKAGE_BASENAME}.tar.gz" ] || [[ $(sha256sum "${BOOST_PACKAGE_BASENAME}.tar.gz" | cut -d " " -f 1 ) != "${BOOST_SHA256SUM}" ]] ; then
        log "Using boost backup"

        start=$(date +%s)
        wget "https://carla-releases.s3.us-east-005.backblazeb2.com/Backup/${BOOST_PACKAGE_BASENAME}.tar.gz" -O ${BOOST_PACKAGE_BASENAME}.tar.gz || true
        end=$(date +%s)
        echo "Elapsed Time downloading from boost carla backup in backblaze: $(($end-$start)) seconds"
      fi
    fi
  fi

  BOOST_CXXFLAGS="${CARLA_CFLAGS} ${CARLA_CXXFLAGS}"

  if { ${SHOULD_BUILD_BOOST_SERVER} ; } ; then
    rm -Rf ${BOOST_BASENAME}-server-source

    log "Extracting boost for server build."
    start=$(date +%s)
    tar -xzf ${BOOST_PACKAGE_BASENAME}.tar.gz
    end=$(date +%s)
    echo "Elapsed Time Extracting boost for server build: $(($end-$start)) seconds"

    mkdir -p ${BOOST_BASENAME}-server-install/include
    mv ${BOOST_PACKAGE_BASENAME} ${BOOST_BASENAME}-server-source

    pushd ${BOOST_BASENAME}-server-source >/dev/null

    BOOST_TOOLSET="clang-10.0"

    # Not so easy to convince Boost bootstrap to use a custom clang with custom flags.
    sed -i 's/\${TOOLSET}/--cxxflags="\${CARLA_CXXFLAGS}" --cxx=\${CARLA_SERVER_CXX} \${TOOLSET}/g' ./bootstrap.sh
    CARLA_CXXFLAGS="${BOOST_CXXFLAGS} ${CARLA_SERVER_CXXFLAGS} ${UNREAL_HOSTED_LINKER_FLAGS} -pthread" CARLA_SERVER_CXX=${CARLA_SERVER_CXX} ./bootstrap.sh \
        --with-toolset=clang \
        --prefix=../${BOOST_BASENAME}-server-install \
        --with-libraries=system
        
    # Similarly, pass the custom clang and flags to b2.
    sed -i 's#using clang#using clang\n  : 10.0\n   : \"'"${CARLA_SERVER_CXX}"'\"\n  : <cxxflags>\"'"${BOOST_CXXFLAGS} ${CARLA_SERVER_CXXFLAGS}"'\"\n    <linkflags>\"'"${UNREAL_HOSTED_LINKER_FLAGS}"'\"\n#g' project-config.jam

    ./b2 toolset="${BOOST_TOOLSET}" -j ${CARLA_BUILD_CONCURRENCY} stage release
    ./b2 toolset="${BOOST_TOOLSET}" -j ${CARLA_BUILD_CONCURRENCY} install

    popd >/dev/null
    rm -Rf ${BOOST_BASENAME}-server-source
  fi

  if { ${SHOULD_BUILD_BOOST_CLIENT} ; } ; then
    rm -Rf ${BOOST_BASENAME}-client-source

    log "Extracting boost for client with Python ${PY_VERSION}."
    start=$(date +%s)
    tar -xzf ${BOOST_PACKAGE_BASENAME}.tar.gz
    end=$(date +%s)
    echo "Elapsed Time Extracting boost for Python: $(($end-$start)) seconds"

    mkdir -p ${BOOST_BASENAME}-client-install/include
    mv ${BOOST_PACKAGE_BASENAME} ${BOOST_BASENAME}-client-source
    
    pushd ${BOOST_BASENAME}-client-source >/dev/null

    BOOST_CFLAGS="-fPIC -std=c++17 -DBOOST_ERROR_CODE_HEADER_ONLY"

    py3="/usr/bin/env python${PY_VERSION}"
    py3_root=`${py3} -c "import sysconfig; print(sysconfig.get_config_var('prefix'))"`
    py3_include=$(${py3} -c "from sysconfig import get_paths as gp; print(gp()['include'])")
    py3_lib=$(${py3} -c "from sysconfig import get_paths as gp; print(gp()['stdlib'])")
    pyv=`$py3 -c "import sys;x='{v[0]}.{v[1]}'.format(v=list(sys.version_info[:2]));sys.stdout.write(x)";`
    
    ./bootstrap.sh \
        --with-toolset=gcc \
        --prefix=../${BOOST_BASENAME}-client-install \
        --with-libraries=python,filesystem,system,program_options \
        --with-python=${py3} --with-python-root=${py3_root}
    if ${TRAVIS} ; then
        echo "using python : ${pyv} : ${py3_root}/bin/python${PY_VERSION} : \
        ${py3_include} : ${py3_lib} ;" > ${HOME}/user-config.jam
    else
        echo "using python : ${pyv} : ${py3_root}/bin/python${PY_VERSION} : \
        ${py3_include} : ${py3_lib} ;" > project-config.jam
    fi

    ./b2 toolset="gcc" cxxflags="${BOOST_CXXFLAGS}" -j ${CARLA_BUILD_CONCURRENCY} stage release
    ./b2 toolset="gcc" cxxflags="${BOOST_CXXFLAGS}" -j ${CARLA_BUILD_CONCURRENCY} install

    popd >/dev/null
    rm -Rf ${BOOST_BASENAME}-client-source

    # Install boost dependencies
    mkdir -p "${LIBCARLA_INSTALL_CLIENT_FOLDER}/include/system"
    mkdir -p "${LIBCARLA_INSTALL_CLIENT_FOLDER}/lib"
    cp -rf ${BOOST_BASENAME}-client-install/include/* ${LIBCARLA_INSTALL_CLIENT_FOLDER}/include/system
    cp -rf ${BOOST_BASENAME}-client-install/lib/* ${LIBCARLA_INSTALL_CLIENT_FOLDER}/lib
  fi

done
if [ -f "${BOOST_PACKAGE_BASENAME}.tar.gz" ]; then
  rm ${BOOST_PACKAGE_BASENAME}.tar.gz
fi

unset BOOST_BASENAME

# ==============================================================================
# -- Get rpclib and compile it with libc++ and libstdc++ -----------------------
# ==============================================================================

RPCLIB_PATCH=carla-callbacks
RPCLIB_BASENAME=rpclib-${RPCLIB_PATCH}

RPCLIB_SERVER_INCLUDE=${PWD}/${RPCLIB_BASENAME}-server-install/include
RPCLIB_SERVER_LIBPATH=${PWD}/${RPCLIB_BASENAME}-server-install/lib
RPCLIB_CLIENT_INCLUDE=${PWD}/${RPCLIB_BASENAME}-client-install/include
RPCLIB_CLIENT_LIBPATH=${PWD}/${RPCLIB_BASENAME}-client-install/lib

if [[ -d "${RPCLIB_BASENAME}-server-install" && -d "${RPCLIB_BASENAME}-client-install" ]] ; then
  log "${RPCLIB_BASENAME} already installed."
else
  rm -Rf \
      ${RPCLIB_BASENAME}-source \
      ${RPCLIB_BASENAME}-server-build ${RPCLIB_BASENAME}-client-build \
      ${RPCLIB_BASENAME}-server-install ${RPCLIB_BASENAME}-client-install

  log "Retrieving rpclib."

  start_download_time=$(date +%s)

  git clone -b ${RPCLIB_PATCH} https://github.com/carla-simulator/rpclib.git ${RPCLIB_BASENAME}-source

  end_download_time=$(date +%s)

  echo "Elapsed Time downloading rpclib: $(($end_download_time-$start_download_time)) seconds"
  log "Building rpclib with libc++."

  # rpclib does not use any cmake 3.9 feature.
  # As cmake 3.9 is not standard in Ubuntu 16.04, change cmake version to 3.5
  sed -i s/"3.9.0"/"3.5.0"/g ${RPCLIB_BASENAME}-source/CMakeLists.txt

  mkdir -p ${RPCLIB_BASENAME}-server-build

  pushd ${RPCLIB_BASENAME}-server-build >/dev/null

  cmake -G "Ninja" \
      -DCMAKE_INSTALL_PREFIX="../${RPCLIB_BASENAME}-server-install" \
      -DCMAKE_TOOLCHAIN_FILE="${CARLA_SERVER_TOOLCHAIN_FILE}" \
      ../${RPCLIB_BASENAME}-source

  ninja

  ninja install

  popd >/dev/null

  log "Building rpclib with libstdc++."

  mkdir -p ${RPCLIB_BASENAME}-client-build

  pushd ${RPCLIB_BASENAME}-client-build >/dev/null

  cmake -G "Ninja" \
      -DCMAKE_INSTALL_PREFIX="../${RPCLIB_BASENAME}-client-install" \
      -DCMAKE_TOOLCHAIN_FILE="${CARLA_CLIENT_TOOLCHAIN_FILE}" \
      ../${RPCLIB_BASENAME}-source

  ninja

  ninja install

  popd >/dev/null

  rm -Rf ${RPCLIB_BASENAME}-source ${RPCLIB_BASENAME}-server-build ${RPCLIB_BASENAME}-client-build

fi

unset RPCLIB_BASENAME

# ==============================================================================
# -- Get GTest and compile it with libc++ --------------------------------------
# ==============================================================================

GTEST_VERSION=1.8.1
GTEST_BASENAME=gtest-${GTEST_VERSION}

GTEST_SERVER_INCLUDE=${PWD}/${GTEST_BASENAME}-server-install/include
GTEST_SERVER_LIBPATH=${PWD}/${GTEST_BASENAME}-server-install/lib
GTEST_CLIENT_INCLUDE=${PWD}/${GTEST_BASENAME}-client-install/include
GTEST_CLIENT_LIBPATH=${PWD}/${GTEST_BASENAME}-client-install/lib

if [[ -d "${GTEST_BASENAME}-server-install" && -d "${GTEST_BASENAME}-client-install" ]] ; then
  log "${GTEST_BASENAME} already installed."
else
  rm -Rf \
      ${GTEST_BASENAME}-source \
      ${GTEST_BASENAME}-server-build ${GTEST_BASENAME}-client-build \
      ${GTEST_BASENAME}-server-install ${GTEST_BASENAME}-client-install

  log "Retrieving Google Test."

  start_download_time=$(date +%s)

  git clone --depth=1 -b release-${GTEST_VERSION} https://github.com/google/googletest.git ${GTEST_BASENAME}-source

  end_download_time=$(date +%s)
  echo "Elapsed Time downloading rpclib: $(($end_download_time-$start_download_time)) seconds"

  log "Building Google Test with libc++."

  mkdir -p ${GTEST_BASENAME}-server-build

  pushd ${GTEST_BASENAME}-server-build >/dev/null

  cmake -G "Ninja" \
      -DCMAKE_INSTALL_PREFIX="../${GTEST_BASENAME}-server-install" \
      -DCMAKE_TOOLCHAIN_FILE="${CARLA_SERVER_TOOLCHAIN_FILE}" \
      ../${GTEST_BASENAME}-source

  ninja

  ninja install

  popd >/dev/null

  log "Building Google Test with libstdc++."

  mkdir -p ${GTEST_BASENAME}-client-build

  pushd ${GTEST_BASENAME}-client-build >/dev/null

  cmake -G "Ninja" \
      -DCMAKE_INSTALL_PREFIX="../${GTEST_BASENAME}-client-install" \
      -DCMAKE_TOOLCHAIN_FILE="${CARLA_CLIENT_TOOLCHAIN_FILE}" \
      ../${GTEST_BASENAME}-source

  ninja

  ninja install

  popd >/dev/null

  rm -Rf ${GTEST_BASENAME}-source ${GTEST_BASENAME}-server-build ${GTEST_BASENAME}-client-build

fi

unset GTEST_BASENAME

# ==============================================================================
# -- Get Recast&Detour and compile it with libc++ ------------------------------
# ==============================================================================

RECAST_BASENAME=recast

RECAST_INCLUDE=${PWD}/${RECAST_BASENAME}-install/include
RECAST_LIBPATH=${PWD}/${RECAST_BASENAME}-install/lib

if [[ -d "${RECAST_BASENAME}-install" &&
      -f "${RECAST_BASENAME}-install/bin/RecastBuilder" ]] ; then
  log "${RECAST_BASENAME} already installed."
else
  rm -Rf \
      ${RECAST_BASENAME}-source \
      ${RECAST_BASENAME}-build \
      ${RECAST_BASENAME}-install

  log "Retrieving Recast & Detour"

  start=$(date +%s)

  git clone --depth 1 -b carla https://github.com/carla-simulator/recastnavigation.git ${RECAST_BASENAME}-source

  end=$(date +%s)
  echo "Elapsed Time downloading: $(($end-$start)) seconds"

  pushd ${RECAST_BASENAME}-source >/dev/null

  popd >/dev/null

  log "Building Recast & Detour with libc++."

  mkdir -p ${RECAST_BASENAME}-build

  pushd ${RECAST_BASENAME}-build >/dev/null

  cmake -G "Ninja" \
      -DCMAKE_INSTALL_PREFIX="../${RECAST_BASENAME}-install" \
      -DCMAKE_TOOLCHAIN_FILE="${CARLA_CLIENT_TOOLCHAIN_FILE}" \
      -DRECASTNAVIGATION_DEMO=False \
      -DRECASTNAVIGATION_TEST=False \
      ../${RECAST_BASENAME}-source

  ninja

  ninja install

  popd >/dev/null

  rm -Rf ${RECAST_BASENAME}-source ${RECAST_BASENAME}-build

fi

# make sure the RecastBuilder is corrctly copied
RECAST_INSTALL_DIR="${CARLA_BUILD_FOLDER}/../Util/DockerUtils/dist"
if [[ ! -f "${RECAST_INSTALL_DIR}/RecastBuilder" ]]; then
  cp "${RECAST_BASENAME}-install/bin/RecastBuilder" "${RECAST_INSTALL_DIR}/"
fi

unset RECAST_BASENAME

# ==============================================================================
# -- Get and compile libpng 1.6.37 ------------------------------
# ==============================================================================

LIBPNG_VERSION=1.6.37
LIBPNG_REPO=https://sourceforge.net/projects/libpng/files/libpng16/older-releases/${LIBPNG_VERSION}/libpng-${LIBPNG_VERSION}.tar.xz
LIBPNG_BASENAME=libpng-${LIBPNG_VERSION}
LIBPNG_INSTALL=${LIBPNG_BASENAME}-install

LIBPNG_INCLUDE=${PWD}/${LIBPNG_BASENAME}-install/include/
LIBPNG_LIBPATH=${PWD}/${LIBPNG_BASENAME}-install/lib

if [[ -d ${LIBPNG_INSTALL} ]] ; then
  log "Libpng already installed."
else
  log "Retrieving libpng."

  start=$(date +%s)
  wget ${LIBPNG_REPO}
  end=$(date +%s)
  echo "Elapsed Time downloading libpng: $(($end-$start)) seconds"

  start=$(date +%s)
  log "Extracting libpng."
  tar -xf libpng-${LIBPNG_VERSION}.tar.xz
  end=$(date +%s)
  echo "Elapsed Time Extracting libpng: $(($end-$start)) seconds"

  mv ${LIBPNG_BASENAME} ${LIBPNG_BASENAME}-source

  pushd ${LIBPNG_BASENAME}-source >/dev/null

  ./configure --prefix=${CARLA_BUILD_FOLDER}/${LIBPNG_INSTALL}
  make install

  popd >/dev/null

  rm -Rf libpng-${LIBPNG_VERSION}.tar.xz
  rm -Rf ${LIBPNG_BASENAME}-source
fi

# ==============================================================================
# -- Get and compile libxerces 3.2.3 ------------------------------
# ==============================================================================

XERCESC_VERSION=3.2.3
XERCESC_BASENAME=xerces-c-${XERCESC_VERSION}

XERCESC_TEMP_FOLDER=${XERCESC_BASENAME}
XERCESC_REPO=https://archive.apache.org/dist/xerces/c/3/sources/xerces-c-${XERCESC_VERSION}.tar.gz

XERCESC_SRC_DIR=${XERCESC_BASENAME}-source
XERCESC_INSTALL_CLIENT_DIR=${XERCESC_BASENAME}-client-install
XERCESC_INSTALL_SERVER_DIR=${XERCESC_BASENAME}-server-install
XERCESC_CLIENT_LIB=${XERCESC_INSTALL_CLIENT_DIR}/lib/libxerces-c.a
XERCESC_SERVER_LIB=${XERCESC_INSTALL_SERVER_DIR}/lib/libxerces-c.a

if [[ -d ${XERCESC_INSTALL_CLIENT_DIR} &&  -d ${XERCESC_INSTALL_SERVER_DIR} ]] ; then
  log "Xerces-c already installed."
else
  log "Retrieving xerces-c."
  start=$(date +%s)
  wget ${XERCESC_REPO}
  end=$(date +%s)
  echo "Elapsed Time downloading from xerces repo: $(($end-$start)) seconds"
  # try to use the backup boost we have in Jenkins
  if [[ ! -f "${XERCESC_BASENAME}.tar.gz" ]] ; then
    log "Using xerces backup"
    start=$(date +%s)
    wget "https://carla-releases.s3.us-east-005.backblazeb2.com/Backup/${XERCESC_BASENAME}.tar.gz" || true
    end=$(date +%s)
    echo "Elapsed Time downloading from xerces backup: $(($end-$start)) seconds"
  fi

  log "Extracting xerces-c."

  start=$(date +%s)
  tar -xzf ${XERCESC_BASENAME}.tar.gz
  end=$(date +%s)
  echo "Elapsed Time Extracting xerces-c: $(($end-$start)) seconds"

  mv ${XERCESC_BASENAME} ${XERCESC_SRC_DIR}
  mkdir -p ${XERCESC_INSTALL_CLIENT_DIR}

  mkdir -p ${XERCESC_SRC_DIR}/client-build
  pushd ${XERCESC_SRC_DIR}/client-build >/dev/null

  cmake -G "Ninja" \
      -DCMAKE_INSTALL_PREFIX="../../${XERCESC_INSTALL_CLIENT_DIR}" \
      -DCMAKE_TOOLCHAIN_FILE="${CARLA_CLIENT_TOOLCHAIN_FILE}" \
      -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_SHARED_LIBS=OFF \
      -Dtranscoder=gnuiconv \
      -Dnetwork=OFF \
      ..
  ninja
  ninja install

  popd >/dev/null

  mkdir -p ${XERCESC_INSTALL_SERVER_DIR}


  mkdir -p ${XERCESC_SRC_DIR}/server-build
  pushd ${XERCESC_SRC_DIR}/server-build >/dev/null

  cmake -G "Ninja" \
      -DCMAKE_INSTALL_PREFIX="../../${XERCESC_INSTALL_SERVER_DIR}" \
      -DCMAKE_TOOLCHAIN_FILE="${CARLA_SERVER_TOOLCHAIN_FILE}" \
      -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_SHARED_LIBS=OFF \
      -Dtranscoder=gnuiconv \
      -Dnetwork=OFF \
      ..
  ninja
  ninja install

  popd >/dev/null

  rm -Rf ${XERCESC_BASENAME}.tar.gz
  rm -Rf ${XERCESC_SRC_DIR}
fi

mkdir -p ${LIBCARLA_INSTALL_CLIENT_FOLDER}/lib/
cp ${XERCESC_CLIENT_LIB} ${LIBCARLA_INSTALL_CLIENT_FOLDER}/lib/

mkdir -p ${LIBCARLA_INSTALL_SERVER_FOLDER}/lib/
cp -p ${XERCESC_SERVER_LIB} ${LIBCARLA_INSTALL_SERVER_FOLDER}/lib/

# ==============================================================================
# -- Get Eigen headers 3.1.0 (CARLA dependency) -------------------------------------
# ==============================================================================
EIGEN_VERSION=3.3.7
EIGEN_REPO=https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.gz
EIGEN_BASENAME=eigen-${EIGEN_VERSION}

EIGEN_SRC_DIR=eigen-${EIGEN_VERSION}-src
EIGEN_INSTALL_DIR=eigen-${EIGEN_VERSION}-install
EIGEN_INCLUDE=${EIGEN_INSTALL_DIR}/include


if [[ -d ${EIGEN_INSTALL_DIR} ]] ; then
    log "Eigen already installed."
else
    log "Retrieving Eigen."

    start=$(date +%s)
    wget ${EIGEN_REPO}
    end=$(date +%s)
    echo "Elapsed Time: $(($end-$start)) seconds"

    log "Extracting Eigen."

    start=$(date +%s)
    tar -xzf ${EIGEN_BASENAME}.tar.gz
    end=$(date +%s)
    echo "Elapsed Time Extracting for Eigen: $(($end-$start)) seconds"

    mv ${EIGEN_BASENAME} ${EIGEN_SRC_DIR}
    mkdir -p ${EIGEN_INCLUDE}/unsupported
    mv ${EIGEN_SRC_DIR}/Eigen ${EIGEN_INCLUDE}
    mv ${EIGEN_SRC_DIR}/unsupported/Eigen ${EIGEN_INCLUDE}/unsupported/Eigen

    rm -Rf ${EIGEN_BASENAME}.tar.gz
    rm -Rf ${EIGEN_SRC_DIR}
fi

mkdir -p ${LIBCARLA_INSTALL_SERVER_FOLDER}/include/
cp -p -r ${EIGEN_INCLUDE}/* ${LIBCARLA_INSTALL_SERVER_FOLDER}/include/

if ${USE_CHRONO} ; then
  # ==============================================================================
  # -- Get Eigen headers (Chrono dependency) -------------------------------------
  # ==============================================================================
  CHRONO_INSTALL_DIR=chrono-install
  if [[ -d ${CHRONO_INSTALL_DIR} ]] ; then
    log "chrono library already installed."
  else
    if [[ -n "${CHRONO_PATH}" ]] ; then
      log "Using user-provided Chrono at: ${CHRONO_PATH}"
      CHRONO_SRC_DIR="${CHRONO_PATH}"
    else
      # ==============================================================================
      # -- Get Chrono and compile it with libc++ -------------------------------------
      # ==============================================================================
      CHRONO_TAG=6.0.0
      CHRONO_REPO=https://github.com/projectchrono/chrono.git
      CHRONO_SRC_DIR=chrono-source
      if [[ -d ${CHRONO_INSTALL_DIR} ]] ; then
        log "chrono library already installed."
      else
        log "Retrieving chrono library."
        start=$(date +%s)
        git clone --depth 1 --branch ${CHRONO_TAG} ${CHRONO_REPO} ${CHRONO_SRC_DIR}
        end=$(date +%s)
        echo "Elapsed Time dowloading chrono: $(($end-$start)) seconds"
      fi
    fi
    EIGEN_INCLUDE=$(realpath "${EIGEN_INSTALL_DIR}/include")
    mkdir -p ${CHRONO_SRC_DIR}/build
    pushd ${CHRONO_SRC_DIR}/build >/dev/null
    cmake -G "Ninja" \
      -DCMAKE_TOOLCHAIN_FILE="${CARLA_SERVER_TOOLCHAIN_FILE}" \
      -DCMAKE_CXX_FLAGS="-Wno-unused-command-line-argument" \
      -DEIGEN3_INCLUDE_DIR="${EIGEN_INCLUDE}" \
      -DCMAKE_INSTALL_PREFIX="${CARLA_BUILD_FOLDER}/${CHRONO_INSTALL_DIR}" \
      -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_DEMOS=OFF \
      -DENABLE_MODULE_VEHICLE=ON \
      ..
    ninja
    ninja install
    popd >/dev/null
    if [[ -n "${CHRONO_PATH}" ]] ; then
      log "Skipping src removal."
    else
      rm -Rf ${CHRONO_SRC_DIR}
    fi
    mkdir -p ${LIBCARLA_INSTALL_SERVER_FOLDER}/lib/
    mkdir -p ${LIBCARLA_INSTALL_SERVER_FOLDER}/include/
    cp -p ${CHRONO_INSTALL_DIR}/lib/*.so ${LIBCARLA_INSTALL_SERVER_FOLDER}/lib/
    cp -p -r ${CHRONO_INSTALL_DIR}/include/* ${LIBCARLA_INSTALL_SERVER_FOLDER}/include/
  fi
fi

# ==============================================================================
# -- Get and compile Sqlite3 ---------------------------------------------------
# ==============================================================================

SQLITE_VERSION=sqlite-autoconf-3340100
SQLITE_REPO=https://www.sqlite.org/2021/${SQLITE_VERSION}.tar.gz
SQLITE_TAR=${SQLITE_VERSION}.tar.gz
SQLITE_BASENAME=sqlite

SQLITE_SERVER_INCLUDE_DIR=${PWD}/${SQLITE_BASENAME}-server-install/include
SQLITE_SERVER_LIB=${PWD}/${SQLITE_BASENAME}-server-install/lib/libsqlite3.a
SQLITE_SERVER_LIB_FOLDER=${PWD}/${SQLITE_BASENAME}-server-install/lib/
SQLITE_CLIENT_INCLUDE_DIR=${PWD}/${SQLITE_BASENAME}-client-install/include
SQLITE_CLIENT_LIB=${PWD}/${SQLITE_BASENAME}-client-install/lib/libsqlite3.a
SQLITE_EXE=${PWD}/${SQLITE_BASENAME}-client-install/bin/sqlite3

if [[ -d ${SQLITE_BASENAME}-server-install && -d ${SQLITE_BASENAME}-client-install ]] ; then
  log "Sqlite already installed."
else
  rm -Rf \
      ${SQLITE_BASENAME}-source \
      ${SQLITE_BASENAME}-build  \
      ${SQLITE_BASENAME}-client-install \
      ${SQLITE_BASENAME}-server-install

  log "Retrieving Sqlite3"

  start=$(date +%s)
  wget ${SQLITE_REPO}
  end=$(date +%s)
  echo "Elapsed Time: $(($end-$start)) seconds"

  log "Extracting Sqlite3"

  start=$(date +%s)
  tar -xzf ${SQLITE_TAR}
  end=$(date +%s)
  echo "Elapsed Time Extracting for SQlite: $(($end-$start)) seconds"

  mv ${SQLITE_VERSION} ${SQLITE_BASENAME}-source

  mkdir ${SQLITE_BASENAME}-client-build
  pushd ${SQLITE_BASENAME}-client-build >/dev/null
  ../${SQLITE_BASENAME}-source/configure CFLAGS="${CARLA_CFLAGS} -w" --prefix=${PWD}/../${SQLITE_BASENAME}-client-install/
  make install
  popd >/dev/null

  mkdir ${SQLITE_BASENAME}-server-build
  pushd ${SQLITE_BASENAME}-server-build >/dev/null
  ../${SQLITE_BASENAME}-source/configure CFLAGS="${CARLA_SERVER_CFLAGS} -w" --prefix=${PWD}/../${SQLITE_BASENAME}-server-install/
  make install
  popd >/dev/null


  rm -Rf ${SQLITE_TAR}
  rm -Rf ${SQLITE_BASENAME}-source ${SQLITE_BASENAME}-client-build ${SQLITE_BASENAME}-server-build
fi

cp ${SQLITE_CLIENT_LIB} ${LIBCARLA_INSTALL_CLIENT_FOLDER}/lib/
cp -p -r ${SQLITE_SERVER_LIB_FOLDER}/* ${LIBCARLA_INSTALL_SERVER_FOLDER}/lib/


# ==============================================================================
# -- Get and compile PROJ ------------------------------------------------------
# ==============================================================================

PROJ_VERSION=proj-7.2.1
PROJ_REPO=https://download.osgeo.org/proj/${PROJ_VERSION}.tar.gz

PROJ_TAR=${PROJ_VERSION}.tar.gz
PROJ_SRC_DIR=proj-src
PROJ_INSTALL_CLIENT_DIR=proj-client-install
PROJ_INSTALL_SERVER_DIR=proj-server-install
PROJ_INSTALL_CLIENT_DIR_FULL=${PWD}/${PROJ_INSTALL_CLIENT_DIR}
PROJ_INSTALL_SERVER_DIR_FULL=${PWD}/${PROJ_INSTALL_SERVER_DIR}
PROJ_CLIENT_LIB=${PROJ_INSTALL_CLIENT_DIR_FULL}/lib/libproj.a
PROJ_SERVER_LIB=${PROJ_INSTALL_SERVER_DIR_FULL}/lib/libproj.a

if [[ -d ${PROJ_INSTALL_CLIENT_DIR} && -d ${PROJ_INSTALL_SERVER_DIR_FULL} ]] ; then
  log "PROJ already installed."
else
  log "Retrieving PROJ"

  start=$(date +%s)
  wget ${PROJ_REPO}
  end=$(date +%s)
  echo "Elapsed Time: $(($end-$start)) seconds"

  log "Extracting PROJ"
  start=$(date +%s)
  tar -xzf ${PROJ_TAR}
  end=$(date +%s)
  echo "Elapsed Time Extracting for PROJ: $(($end-$start)) seconds"

  mv ${PROJ_VERSION} ${PROJ_SRC_DIR}
  # fix missing include
  sed -e 's/#include <string>/#include <string>\n#include <cstdint>/g' -i ${PROJ_SRC_DIR}/src/proj_json_streaming_writer.hpp

  mkdir -p ${PROJ_SRC_DIR}/client-build
  mkdir -p ${PROJ_INSTALL_CLIENT_DIR}

  pushd ${PROJ_SRC_DIR}/client-build >/dev/null

  cmake -G "Ninja" .. \
      -DCMAKE_TOOLCHAIN_FILE="${CARLA_CLIENT_TOOLCHAIN_FILE}" \
      -DSQLITE3_INCLUDE_DIR=${SQLITE_CLIENT_INCLUDE_DIR} -DSQLITE3_LIBRARY=${SQLITE_CLIENT_LIB} \
      -DEXE_SQLITE3=${SQLITE_EXE} \
      -DENABLE_TIFF=OFF -DENABLE_CURL=OFF -DBUILD_SHARED_LIBS=OFF -DBUILD_PROJSYNC=OFF \
      -DCMAKE_BUILD_TYPE=Release -DBUILD_PROJINFO=OFF \
      -DBUILD_CCT=OFF -DBUILD_CS2CS=OFF -DBUILD_GEOD=OFF -DBUILD_GIE=OFF \
      -DBUILD_PROJ=OFF -DBUILD_TESTING=OFF \
      -DCMAKE_INSTALL_PREFIX=${PROJ_INSTALL_CLIENT_DIR_FULL}
  ninja
  ninja install

  popd >/dev/null

  mkdir -p ${PROJ_INSTALL_SERVER_DIR}

  mkdir -p ${PROJ_SRC_DIR}/server-build
  pushd ${PROJ_SRC_DIR}/server-build >/dev/null

  cmake -G "Ninja" .. \
      -DCMAKE_TOOLCHAIN_FILE="${CARLA_SERVER_TOOLCHAIN_FILE}" \
      -DSQLITE3_INCLUDE_DIR=${SQLITE_SERVER_INCLUDE_DIR} -DSQLITE3_LIBRARY=${SQLITE_SERVER_LIB} \
      -DEXE_SQLITE3=${SQLITE_EXE} \
      -DENABLE_TIFF=OFF -DENABLE_CURL=OFF -DBUILD_SHARED_LIBS=OFF -DBUILD_PROJSYNC=OFF \
      -DCMAKE_BUILD_TYPE=Release -DBUILD_PROJINFO=OFF \
      -DBUILD_CCT=OFF -DBUILD_CS2CS=OFF -DBUILD_GEOD=OFF -DBUILD_GIE=OFF \
      -DBUILD_PROJ=OFF -DBUILD_TESTING=OFF \
      -DCMAKE_INSTALL_PREFIX=${PROJ_INSTALL_SERVER_DIR_FULL}
  ninja
  ninja install

  popd >/dev/null

  rm -Rf ${PROJ_TAR}
  rm -Rf ${PROJ_SRC_DIR}

fi

cp ${PROJ_CLIENT_LIB} ${LIBCARLA_INSTALL_CLIENT_FOLDER}/lib/

mkdir -p ${LIBCARLA_INSTALL_SERVER_FOLDER}/lib/
cp -p ${PROJ_SERVER_LIB} ${LIBCARLA_INSTALL_SERVER_FOLDER}/lib/

# ==============================================================================
# -- Get and compile patchelf --------------------------------------------------
# ==============================================================================

PATCHELF_VERSION=0.12
PATCHELF_REPO=https://github.com/NixOS/patchelf/archive/${PATCHELF_VERSION}.tar.gz

PATCHELF_TAR=${PATCHELF_VERSION}.tar.gz
PATCHELF_SOURCE_DIR=patchelf-src
PATCHELF_INSTALL_DIR=patchelf-install

PATCHELF_INCLUDE_DIR=${PWD}/${PATCHELF_INSTALL_DIR}/include
PATCHELF_EXE=${PWD}/${PATCHELF_INSTALL_DIR}/bin/patchelf

if [[ -d ${PATCHELF_INSTALL_DIR} ]] ; then
  log "Patchelf already installed."
else
  log "Retrieving patchelf"

  start=$(date +%s)
  wget ${PATCHELF_REPO}
  end=$(date +%s)
  echo "Elapsed Time: $(($end-$start)) seconds"

  log "Extracting patchelf"
  start=$(date +%s)
  tar -xzf ${PATCHELF_TAR}
  end=$(date +%s)
  echo "Elapsed Time Extracting patchelf: $(($end-$start)) seconds"

  mv patchelf-${PATCHELF_VERSION} ${PATCHELF_SOURCE_DIR}

  mkdir ${PATCHELF_INSTALL_DIR}

  pushd ${PATCHELF_SOURCE_DIR} >/dev/null

  ./bootstrap.sh
  ./configure --prefix=${PWD}/../${PATCHELF_INSTALL_DIR}
  make
  make install

  popd >/dev/null

  rm -Rf ${PATCHELF_TAR}
  rm -Rf ${PATCHELF_SOURCE_DIR}
fi

mkdir -p ${LIBCARLA_INSTALL_CLIENT_FOLDER}/bin/
cp ${PATCHELF_EXE} ${LIBCARLA_INSTALL_CLIENT_FOLDER}/bin/

# ==============================================================================
# -- Download libtorch and dependencies ----------------------------------------
# ==============================================================================

if ${USE_PYTORCH} ; then

  LIBTORCH_BASENAME=libtorch

  LIBTORCH_PATH=${PWD}/${LIBTORCH_BASENAME}
  LIBTORCH_INCLUDE=${LIBTORCH_PATH}/include
  LIBTORCH_LIB=${LIBTORCH_PATH}/lib
  LIBTORCH_ZIPFILE=libtorch-shared-with-deps-1.11.0+cu113.zip
  LIBTORCH_REPO=https://download.pytorch.org/libtorch/cu113/libtorch-shared-with-deps-1.11.0%2Bcu113.zip
  if [[ ! -d ${LIBTORCH_PATH} ]] ; then

    start=$(date +%s)
    wget ${LIBTORCH_REPO}
    end=$(date +%s)
    echo "Elapsed Time downloading LIBTORCH_REPO: $(($end-$start)) seconds"

    unzip ${LIBTORCH_ZIPFILE}
  fi

  function build_torch_extension {

    LIB_SOURCE=$1
    LIB_INSTALL=$2
    LIB_REPO=$3
    if [[ ! -d ${LIB_INSTALL} ]] ; then
      if [[ ! -d ${LIB_SOURCE} ]] ; then
        mkdir -p ${LIB_SOURCE}
        log "${LIB_REPO}"
        git clone ${LIB_REPO} ${LIB_SOURCE}
        mkdir -p ${LIB_SOURCE}/build
      fi
      pushd ${LIB_SOURCE}/build >/dev/null

      cmake -DCMAKE_PREFIX_PATH="${LIBTORCH_PATH}" \
          -DCMAKE_CUDA_COMPILER="/usr/local/cuda/bin/nvcc" \
          -DCMAKE_INSTALL_PREFIX="${LIB_INSTALL}" \
          -DCMAKE_CUDA_FLAGS="-gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_53,code=sm_53 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_62,code=sm_62 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_72,code=sm_72 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_86,code=sm_86 -gencode=arch=compute_87,code=sm_87 -Wno-deprecated-gpu-targets" \
          -DWITH_CUDA=ON \
          ..
      make
      make install
      popd >/dev/null
    fi

  }

  log "Build libtorch scatter"
  #LibtorchScatter
  LIBTORCHSCATTER_BASENAME=libtorchscatter
  LIBTORCHSCATTER_SOURCE_DIR=${PWD}/${LIBTORCHSCATTER_BASENAME}-source
  LIBTORCHSCATTER_INSTALL_DIR=${PWD}/${LIBTORCHSCATTER_BASENAME}-install
  LIBTORCHSCATTER_INCLUDE=${LIBTORCHSCATTER_INSTALL_DIR}/include
  LIBTORCHSCATTER_LIB=${LIBTORCHSCATTER_INSTALL_DIR}/lib
  LIBTORCHSCATTER_REPO="https://github.com/rusty1s/pytorch_scatter.git"

  build_torch_extension ${LIBTORCHSCATTER_SOURCE_DIR} ${LIBTORCHSCATTER_INSTALL_DIR} "${LIBTORCHSCATTER_REPO}"

  log "Build libtorch cluster"
  LIBTORCHCLUSTER_BASENAME=libtorchcluster
  LIBTORCHCLUSTER_SOURCE_DIR=${PWD}/${LIBTORCHCLUSTER_BASENAME}-source
  LIBTORCHCLUSTER_INSTALL_DIR=${PWD}/${LIBTORCHCLUSTER_BASENAME}-install
  LIBTORCHCLUSTER_INCLUDE=${LIBTORCHCLUSTER_INSTALL_DIR}/include
  LIBTORCHCLUSTER_LIB=${LIBTORCHCLUSTER_INSTALL_DIR}/lib
  LIBTORCHCLUSTER_REPO="https://github.com/rusty1s/pytorch_cluster.git"

  build_torch_extension ${LIBTORCHCLUSTER_SOURCE_DIR} ${LIBTORCHCLUSTER_INSTALL_DIR} "${LIBTORCHCLUSTER_REPO}"

  mkdir -p ${LIBCARLA_INSTALL_SERVER_FOLDER}/lib/
  cp -p ${LIBTORCH_LIB}/*.a ${LIBCARLA_INSTALL_SERVER_FOLDER}/lib/
  cp -p ${LIBTORCH_LIB}/*.so* ${LIBCARLA_INSTALL_SERVER_FOLDER}/lib/
  cp -p ${LIBTORCHSCATTER_LIB}/*.so ${LIBCARLA_INSTALL_SERVER_FOLDER}/lib/
  cp -p ${LIBTORCHCLUSTER_LIB}/*.so ${LIBCARLA_INSTALL_SERVER_FOLDER}/lib/

  mkdir -p ${CARLAUE4_PLUGIN_ROOT_FOLDER}/Binaries/Linux/
  cp -p ${LIBTORCH_LIB}/*.so* ${CARLAUE4_PLUGIN_ROOT_FOLDER}/Binaries/Linux/
  cp -p ${LIBTORCHSCATTER_LIB}/*.so* ${CARLAUE4_PLUGIN_ROOT_FOLDER}/Binaries/Linux/
  cp -p ${LIBTORCHCLUSTER_LIB}/*.so* ${CARLAUE4_PLUGIN_ROOT_FOLDER}/Binaries/Linux/
fi

# ==============================================================================
# -- Download Fast DDS and dependencies ----------------------------------------
# ==============================================================================

FASTDDS_BASENAME=fast-dds
FASTDDS_INSTALL_DIR=${PWD}/${FASTDDS_BASENAME}-install
FASTDDS_INCLUDE=${FASTDDS_INSTALL_DIR}/include
FASTDDS_LIB=${FASTDDS_INSTALL_DIR}/lib
if ${USE_ROS2} ; then

  if [[ -d ${FASTDDS_INSTALL_DIR} ]] ; then
    log "FastDDS already installed."
  else
    mkdir -p ${FASTDDS_INSTALL_DIR}

    # foonathan library is not added as a submodule in the fast dds repository so we neet to handle it ourselves.
    log "Building foonathan memory vendor"
    FOONATHAN_MEMORY_VENDOR_BASENAME=foonathan-memory-vendor
    FOONATHAN_MEMORY_VENDOR_SOURCE_DIR=${PWD}/${FOONATHAN_MEMORY_VENDOR_BASENAME}-source
    FOONATHAN_MEMORY_VENDOR_REPO="https://github.com/eProsima/foonathan_memory_vendor.git"
    FOONATHAN_MEMORY_VENDOR_BRANCH=v1.3.2

    git clone --depth 1 --branch ${FOONATHAN_MEMORY_VENDOR_BRANCH} ${FOONATHAN_MEMORY_VENDOR_REPO} ${FOONATHAN_MEMORY_VENDOR_SOURCE_DIR}

    mkdir -p ${FOONATHAN_MEMORY_VENDOR_SOURCE_DIR}/build
    pushd ${FOONATHAN_MEMORY_VENDOR_SOURCE_DIR}/build >/dev/null
    cmake -G "Ninja" \
      -DCMAKE_INSTALL_PREFIX="${FASTDDS_INSTALL_DIR}" \
      -DCMAKE_TOOLCHAIN_FILE=${CARLA_SERVER_TOOLCHAIN_FILE} \
      -DBUILD_SHARED_LIBS=OFF \
      -DFOONATHAN_MEMORY_FORCE_VENDORED_BUILD=ON \
      ..
    ninja
    ninja install
    popd >/dev/null
    rm -Rf ${FOONATHAN_MEMORY_VENDOR_SOURCE_DIR}

    log "Building fastdds"
    FAST_DDS_LIB_BASENAME=fast-dds-lib
    FAST_DDS_LIB_SOURCE_DIR=${PWD}/${FAST_DDS_LIB_BASENAME}-source
    FAST_DDS_LIB_REPO="https://github.com/eProsima/Fast-DDS.git"
    FAST_DDS_LIB_BRANCH=v2.14.6
  
    git clone --recurse-submodules --depth 1 --branch ${FAST_DDS_LIB_BRANCH} ${FAST_DDS_LIB_REPO} ${FAST_DDS_LIB_SOURCE_DIR}

    # copy OpenSSL from UE4
    cp -r ${UE4_ROOT}/Engine/Source/ThirdParty/OpenSSL/1.1.1c/include/Linux/x86_64-unknown-linux-gnu/* ${FASTDDS_INCLUDE}
    cp -r ${UE4_ROOT}/Engine/Source/ThirdParty/OpenSSL/1.1.1c/lib/Linux/x86_64-unknown-linux-gnu/* ${FASTDDS_LIB}

    # copy libatomic from UE4
    # cp -r ${UE4_ROOT}/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v17_clang-10.0.1-centos7/x86_64-unknown-linux-gnu/include/c++/4.8.5/atomic ${FASTDDS_INCLUDE}
    # cp -r ${UE4_ROOT}/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v17_clang-10.0.1-centos7/x86_64-unknown-linux-gnu/lib64/libatomic* ${FASTDDS_LIB}

    # we have to tweak the sources a bit to be able to compile with our boost version
    if [[ -e ${FAST_DDS_LIB_SOURCE_DIR}/thirdparty/boost/include/boost ]]; then
      # remove their boost includes, but keep their entry point
      rm -rf ${FAST_DDS_LIB_SOURCE_DIR}/thirdparty/boost/include/boost
    fi

    mkdir -p ${FAST_DDS_LIB_SOURCE_DIR}/build
    pushd ${FAST_DDS_LIB_SOURCE_DIR}/build >/dev/null
    
    # ensure to NOT disable ASIO_EXCEPTIONS and BOOST_EXCEPTIONS for DDS build!
    # because these exceptions are actively deployed within FastDDS to detect e.g. if socket-addresses are already in use, etc.
    # and reacts accordingly if we disable exceptions, occuring exceptions are forwarded to CARLA server and the program gets
    #  finished, which is not desired behaviour
    # => remove -DASIO_NO_EXCEPTIONS and -DBOOST_NO_EXCEPTIONS from toolchain file
    sed -e "s|\-DASIO_NO_EXCEPTIONS||g"  ${CARLA_SERVER_TOOLCHAIN_FILE} > ${CARLA_SERVER_TOOLCHAIN_FILE}.fastdds
    sed -e "s|\-DBOOST_NO_EXCEPTIONS||g"  -i ${CARLA_SERVER_TOOLCHAIN_FILE}.fastdds

    cmake -G "Ninja" \
      -DCMAKE_INSTALL_PREFIX="${FASTDDS_INSTALL_DIR}" \
      -DCMAKE_TOOLCHAIN_FILE=${CARLA_SERVER_TOOLCHAIN_FILE}.fastdds \
      -DBUILD_SHARED_LIBS=OFF \
      -DBUILD_TESTING=OFF \
      -DCOMPILE_EXAMPLES=OFF \
      -DCOMPILE_TOOLS=OFF \
      -DTHIRDPARTY_Asio=FORCE \
      -DTHIRDPARTY_fastcdr=FORCE \
      -DTHIRDPARTY_TinyXML2=FORCE \
      -DSQLITE3_SUPPORT=OFF \
      -DOPENSSL_FOUND:BOOL=ON \
      -DOPENSSL_INCLUDE_DIR:FILEPATH=${FASTDDS_INCLUDE} \
      -DOPENSSL_SSL_LIBRARY:FILEPATH=${FASTDDS_LIB}/libssl.a \
      -DOPENSSL_CRYPTO_LIBRARY:FILEPATH=${FASTDDS_LIB}/libcrypto.a \
      -DTHIRDPARTY_BOOST_INCLUDE_DIR="${BOOST_SERVER_INCLUDE};${FAST_DDS_LIB_SOURCE_DIR}/thirdparty/boost/include" \
      ..
    ninja
    ninja install
    popd >/dev/null
    rm -Rf ${FAST_DDS_LIB_SOURCE_DIR}

    mkdir -p ${LIBCARLA_INSTALL_SERVER_FOLDER}/lib/
    cp -p ${FASTDDS_LIB}/*.a ${LIBCARLA_INSTALL_SERVER_FOLDER}/lib/
    cp -p -r ${FASTDDS_INCLUDE}/* ${LIBCARLA_INSTALL_SERVER_FOLDER}/include/
  fi
fi

# ==============================================================================
# -- Generate Version.h --------------------------------------------------------
# ==============================================================================

CARLA_VERSION=$(get_git_repository_version)

log "CARLA version ${CARLA_VERSION}."

VERSION_H_FILE=${LIBCARLA_ROOT_FOLDER}/source/carla/Version.h
VERSION_H_FILE_GEN=${CARLA_BUILD_FOLDER}/Version.h

sed -e "s|\${CARLA_VERSION}|${CARLA_VERSION}|g" ${VERSION_H_FILE}.in > ${VERSION_H_FILE_GEN}

move_if_changed "${VERSION_H_FILE_GEN}" "${VERSION_H_FILE}"

# ==============================================================================
# -- Generate CMake config -----------------------------------------------------
# ==============================================================================

cat >${CMAKE_CONFIG_FILE}.gen <<EOL
# Automatically generated by `basename "$0"`

add_definitions(-DBOOST_ERROR_CODE_HEADER_ONLY)

if ((CMAKE_BUILD_TYPE STREQUAL "Server") OR (CMAKE_BUILD_TYPE STREQUAL "ros2"))
  add_definitions(-DASIO_NO_EXCEPTIONS)
  add_definitions(-DBOOST_NO_EXCEPTIONS)
  add_definitions(-DLIBCARLA_NO_EXCEPTIONS)
  add_definitions(-DPUGIXML_NO_EXCEPTIONS)
endif ()

# Uncomment to force support for an specific image format (require their
# respective libraries installed).
# add_definitions(-DLIBCARLA_IMAGE_WITH_PNG_SUPPORT)
# add_definitions(-DLIBCARLA_IMAGE_WITH_JPEG_SUPPORT)
# add_definitions(-DLIBCARLA_IMAGE_WITH_TIFF_SUPPORT)

add_definitions(-DLIBCARLA_TEST_CONTENT_FOLDER="${LIBCARLA_TEST_CONTENT_FOLDER}")

if ((CMAKE_BUILD_TYPE STREQUAL "Server") OR (CMAKE_BUILD_TYPE STREQUAL "ros2"))
  # Here libraries linking libc++.
  set(BOOST_INCLUDE_PATH "${BOOST_SERVER_INCLUDE}")
  set(BOOST_LIB_PATH "${BOOST_SERVER_LIBPATH}")
  set(LLVM_INCLUDE_PATH "${LLVM_INCLUDE}")
  set(LLVM_LIB_PATH "${LLVM_LIBPATH}")
  set(RPCLIB_INCLUDE_PATH "${RPCLIB_SERVER_INCLUDE}")
  set(RPCLIB_LIB_PATH "${RPCLIB_SERVER_LIBPATH}")
  set(GTEST_INCLUDE_PATH "${GTEST_SERVER_INCLUDE}")
  set(GTEST_LIB_PATH "${GTEST_SERVER_LIBPATH}")
elseif (CMAKE_BUILD_TYPE STREQUAL "Pytorch")
  set(BOOST_INCLUDE_PATH "${BOOST_SERVER_INCLUDE}")
  set(BOOST_LIB_PATH "${BOOST_SERVER_LIBPATH}")
  list(APPEND CMAKE_PREFIX_PATH "${LIBTORCH_PATH}")
  list(APPEND CMAKE_PREFIX_PATH "${LIBTORCHSCATTER_INSTALL_DIR}")
  list(APPEND CMAKE_PREFIX_PATH "${LIBTORCHCLUSTER_INSTALL_DIR}")
  list(APPEND CMAKE_PREFIX_PATH "${LIBTORCHSPARSE_INSTALL_DIR}")
elseif (CMAKE_BUILD_TYPE STREQUAL "Client")
  # Here libraries linking libstdc++.
  set(BOOST_INCLUDE_PATH "${BOOST_CLIENT_INCLUDE}")
  set(BOOST_LIB_PATH "${BOOST_CLIENT_LIBPATH}")
  set(RPCLIB_INCLUDE_PATH "${RPCLIB_CLIENT_INCLUDE}")
  set(RPCLIB_LIB_PATH "${RPCLIB_CLIENT_LIBPATH}")
  set(GTEST_INCLUDE_PATH "${GTEST_CLIENT_INCLUDE}")
  set(GTEST_LIB_PATH "${GTEST_CLIENT_LIBPATH}")
  set(RECAST_INCLUDE_PATH "${RECAST_INCLUDE}")
  set(RECAST_LIB_PATH "${RECAST_LIBPATH}")
  set(LIBPNG_INCLUDE_PATH "${LIBPNG_INCLUDE}")
  set(LIBPNG_LIB_PATH "${LIBPNG_LIBPATH}")
endif ()

if (CMAKE_BUILD_TYPE STREQUAL "ros2")
  set(FASTDDS_INCLUDE_PATH "${FASTDDS_INCLUDE}")
  set(FASTDDS_LIB_PATH "${FASTDDS_LIB}")
  set(FASTDDS_LIBRARIES "fastrtps" "fastcdr")
endif ()

EOL

if [ "${TRAVIS}" == "true" ] ; then
  log "Travis CI build detected: disabling PNG support."
  echo "add_definitions(-DLIBCARLA_IMAGE_WITH_PNG_SUPPORT=false)" >> ${CMAKE_CONFIG_FILE}.gen
else
  echo "add_definitions(-DLIBCARLA_IMAGE_WITH_PNG_SUPPORT=true)" >> ${CMAKE_CONFIG_FILE}.gen
fi

move_if_changed "${CMAKE_CONFIG_FILE}.gen" "${CMAKE_CONFIG_FILE}"

# ==============================================================================
# -- ...and we are done --------------------------------------------------------
# ==============================================================================

popd >/dev/null

log "Success!"
