// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Clock.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Clock.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

#define builtin_interfaces_msg_Time_max_cdr_typesize 8ULL;
#define rosgraph_msgs_msg_Clock_max_cdr_typesize 8ULL;
#define builtin_interfaces_msg_Time_max_key_cdr_typesize 0ULL;
#define rosgraph_msgs_msg_Clock_max_key_cdr_typesize 0ULL;

rosgraph_msgs::msg::Clock::Clock()
{
    // builtin_interfaces::msg::Time m_clock_time


}

rosgraph_msgs::msg::Clock::~Clock()
{
}

rosgraph_msgs::msg::Clock::Clock(
        const Clock& x)
{
    m_clock_time = x.m_clock_time;
}

rosgraph_msgs::msg::Clock::Clock(
        Clock&& x) noexcept 
{
    m_clock_time = std::move(x.m_clock_time);
}

rosgraph_msgs::msg::Clock& rosgraph_msgs::msg::Clock::operator =(
        const Clock& x)
{

    m_clock_time = x.m_clock_time;

    return *this;
}

rosgraph_msgs::msg::Clock& rosgraph_msgs::msg::Clock::operator =(
        Clock&& x) noexcept
{

    m_clock_time = std::move(x.m_clock_time);

    return *this;
}

bool rosgraph_msgs::msg::Clock::operator ==(
        const Clock& x) const
{

    return (m_clock_time == x.m_clock_time);
}

bool rosgraph_msgs::msg::Clock::operator !=(
        const Clock& x) const
{
    return !(*this == x);
}

size_t rosgraph_msgs::msg::Clock::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return rosgraph_msgs_msg_Clock_max_cdr_typesize;
}

size_t rosgraph_msgs::msg::Clock::getCdrSerializedSize(
        const rosgraph_msgs::msg::Clock& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += builtin_interfaces::msg::Time::getCdrSerializedSize(data.clock_time(), current_alignment);

    return current_alignment - initial_alignment;
}

void rosgraph_msgs::msg::Clock::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_clock_time;

}

void rosgraph_msgs::msg::Clock::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_clock_time;
}

/*!
 * @brief This function copies the value in member clock_time
 * @param _clock_time New value to be copied in member clock_time
 */
void rosgraph_msgs::msg::Clock::clock_time(
        const builtin_interfaces::msg::Time& _clock_time)
{
    m_clock_time = _clock_time;
}

/*!
 * @brief This function moves the value in member clock_time
 * @param _clock_time New value to be moved in member clock_time
 */
void rosgraph_msgs::msg::Clock::clock_time(
        builtin_interfaces::msg::Time&& _clock_time)
{
    m_clock_time = std::move(_clock_time);
}

/*!
 * @brief This function returns a constant reference to member clock_time
 * @return Constant reference to member clock_time
 */
const builtin_interfaces::msg::Time& rosgraph_msgs::msg::Clock::clock_time() const
{
    return m_clock_time;
}

/*!
 * @brief This function returns a reference to member clock_time
 * @return Reference to member clock_time
 */
builtin_interfaces::msg::Time& rosgraph_msgs::msg::Clock::clock_time()
{
    return m_clock_time;
}


size_t rosgraph_msgs::msg::Clock::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return rosgraph_msgs_msg_Clock_max_key_cdr_typesize;
}

bool rosgraph_msgs::msg::Clock::isKeyDefined()
{
    return false;
}

void rosgraph_msgs::msg::Clock::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}



