cc_test(
    name = "CppClient",
    srcs = ["CppClient/main.cpp"],
    size = "small",
    tags = [
        "exclusive",
        "manual",
    ],
    deps = [
        "//LibCarla/source/carla:client",
        "//LibCarla/source/carla:client_io",
        "//LibCarla/source/carla:python3.8",
    ],
)
