#pragma push_macro("InterlockedIncrementAcquire16")
#undef InterlockedIncrementAcquire16
#pragma push_macro("InterlockedIncrementRelease16")
#undef InterlockedIncrementRelease16
#pragma push_macro("InterlockedIncrementNoFence16")
#undef InterlockedIncrementNoFence16
#pragma push_macro("InterlockedDecrement16")
#undef InterlockedDecrement16
#pragma push_macro("InterlockedDecrementAcquire16")
#undef InterlockedDecrementAcquire16
#pragma push_macro("InterlockedDecrementRelease16")
#undef InterlockedDecrementRelease16
#pragma push_macro("InterlockedDecrementNoFence16")
#undef InterlockedDecrementNoFence16
#pragma push_macro("InterlockedCompareExchange16")
#undef InterlockedCompareExchange16
#pragma push_macro("InterlockedCompareExchangeAcquire16")
#undef InterlockedCompareExchangeAcquire16
#pragma push_macro("InterlockedCompareExchangeRelease16")
#undef InterlockedCompareExchangeRelease16
#pragma push_macro("InterlockedCompareExchangeNoFence16")
#undef InterlockedCompareExchangeNoFence16
#pragma push_macro("InterlockedAnd")
#undef InterlockedAnd
#pragma push_macro("InterlockedAndAcquire")
#undef InterlockedAndAcquire
#pragma push_macro("InterlockedAndRelease")
#undef InterlockedAndRelease
#pragma push_macro("InterlockedAndNoFence")
#undef InterlockedAndNoFence
#pragma push_macro("InterlockedOr")
#undef InterlockedOr
#pragma push_macro("InterlockedOrAcquire")
#undef InterlockedOrAcquire
#pragma push_macro("InterlockedOrRelease")
#undef InterlockedOrRelease
#pragma push_macro("InterlockedOrNoFence")
#undef InterlockedOrNoFence
#pragma push_macro("InterlockedXor")
#undef InterlockedXor
#pragma push_macro("InterlockedXorAcquire")
#undef InterlockedXorAcquire
#pragma push_macro("InterlockedXorRelease")
#undef InterlockedXorRelease
#pragma push_macro("InterlockedXorNoFence")
#undef InterlockedXorNoFence
#pragma push_macro("InterlockedIncrement")
#undef InterlockedIncrement
#pragma push_macro("InterlockedIncrementAcquire")
#undef InterlockedIncrementAcquire
#pragma push_macro("InterlockedIncrementRelease")
#undef InterlockedIncrementRelease
#pragma push_macro("InterlockedIncrementNoFence")
#undef InterlockedIncrementNoFence
#pragma push_macro("InterlockedDecrement")
#undef InterlockedDecrement
#pragma push_macro("InterlockedDecrementAcquire")
#undef InterlockedDecrementAcquire
#pragma push_macro("InterlockedDecrementRelease")
#undef InterlockedDecrementRelease
#pragma push_macro("InterlockedDecrementNoFence")
#undef InterlockedDecrementNoFence
#pragma push_macro("InterlockedAdd")
#undef InterlockedAdd
#pragma push_macro("InterlockedAddAcquire")
#undef InterlockedAddAcquire
#pragma push_macro("InterlockedAddRelease")
#undef InterlockedAddRelease
#pragma push_macro("InterlockedAddNoFence")
#undef InterlockedAddNoFence
#pragma push_macro("InterlockedExchange")
#undef InterlockedExchange
#pragma push_macro("InterlockedExchangeAcquire")
#undef InterlockedExchangeAcquire
#pragma push_macro("InterlockedExchangeNoFence")
#undef InterlockedExchangeNoFence
#pragma push_macro("InterlockedExchangeAdd")
#undef InterlockedExchangeAdd
#pragma push_macro("InterlockedExchangeAddAcquire")
#undef InterlockedExchangeAddAcquire
#pragma push_macro("InterlockedExchangeAddRelease")
#undef InterlockedExchangeAddRelease
#pragma push_macro("InterlockedExchangeAddNoFence")
#undef InterlockedExchangeAddNoFence
#pragma push_macro("InterlockedCompareExchange")
#undef InterlockedCompareExchange
#pragma push_macro("InterlockedCompareExchangeAcquire")
#undef InterlockedCompareExchangeAcquire
#pragma push_macro("InterlockedCompareExchangeRelease")
#undef InterlockedCompareExchangeRelease
#pragma push_macro("InterlockedCompareExchangeNoFence")
#undef InterlockedCompareExchangeNoFence
#pragma push_macro("InterlockedAnd64")
#undef InterlockedAnd64
#pragma push_macro("InterlockedAnd64Acquire")
#undef InterlockedAnd64Acquire
#pragma push_macro("InterlockedAnd64Release")
#undef InterlockedAnd64Release
#pragma push_macro("InterlockedAnd64NoFence")
#undef InterlockedAnd64NoFence
#pragma push_macro("InterlockedAndAffinity")
#undef InterlockedAndAffinity
#pragma push_macro("InterlockedOr64")
#undef InterlockedOr64
#pragma push_macro("InterlockedOr64Acquire")
#undef InterlockedOr64Acquire
#pragma push_macro("InterlockedOr64Release")
#undef InterlockedOr64Release
#pragma push_macro("InterlockedOr64NoFence")
#undef InterlockedOr64NoFence
#pragma push_macro("InterlockedOrAffinity")
#undef InterlockedOrAffinity
#pragma push_macro("InterlockedXor64")
#undef InterlockedXor64
#pragma push_macro("InterlockedXor64Acquire")
#undef InterlockedXor64Acquire
#pragma push_macro("InterlockedXor64Release")
#undef InterlockedXor64Release
#pragma push_macro("InterlockedXor64NoFence")
#undef InterlockedXor64NoFence
#pragma push_macro("InterlockedIncrement64")
#undef InterlockedIncrement64
#pragma push_macro("InterlockedIncrementAcquire64")
#undef InterlockedIncrementAcquire64
#pragma push_macro("InterlockedIncrementRelease64")
#undef InterlockedIncrementRelease64
#pragma push_macro("InterlockedIncrementNoFence64")
#undef InterlockedIncrementNoFence64
#pragma push_macro("InterlockedDecrement64")
#undef InterlockedDecrement64
#pragma push_macro("InterlockedDecrementAcquire64")
#undef InterlockedDecrementAcquire64
#pragma push_macro("InterlockedDecrementRelease64")
#undef InterlockedDecrementRelease64
#pragma push_macro("InterlockedDecrementNoFence64")
#undef InterlockedDecrementNoFence64
#pragma push_macro("InterlockedAdd64")
#undef InterlockedAdd64
#pragma push_macro("InterlockedAddAcquire64")
#undef InterlockedAddAcquire64
#pragma push_macro("InterlockedAddRelease64")
#undef InterlockedAddRelease64
#pragma push_macro("InterlockedAddNoFence64")
#undef InterlockedAddNoFence64
#pragma push_macro("InterlockedExchange64")
#undef InterlockedExchange64
#pragma push_macro("InterlockedExchangeAcquire64")
#undef InterlockedExchangeAcquire64
#pragma push_macro("InterlockedExchangeNoFence64")
#undef InterlockedExchangeNoFence64
#pragma push_macro("InterlockedExchangeAdd64")
#undef InterlockedExchangeAdd64
#pragma push_macro("InterlockedExchangeAddAcquire64")
#undef InterlockedExchangeAddAcquire64
#pragma push_macro("InterlockedExchangeAddRelease64")
#undef InterlockedExchangeAddRelease64
#pragma push_macro("InterlockedExchangeAddNoFence64")
#undef InterlockedExchangeAddNoFence64
#pragma push_macro("InterlockedCompareExchange64")
#undef InterlockedCompareExchange64
#pragma push_macro("InterlockedCompareExchangeAcquire64")
#undef InterlockedCompareExchangeAcquire64
#pragma push_macro("InterlockedCompareExchangeRelease64")
#undef InterlockedCompareExchangeRelease64
#pragma push_macro("InterlockedCompareExchangeNoFence64")
#undef InterlockedCompareExchangeNoFence64
#pragma push_macro("InterlockedCompareExchange128")
#undef InterlockedCompareExchange128
#pragma push_macro("InterlockedExchangePointer")
#undef InterlockedExchangePointer
#pragma push_macro("InterlockedExchangePointerNoFence")
#undef InterlockedExchangePointerNoFence
#pragma push_macro("InterlockedExchangePointerAcquire")
#undef InterlockedExchangePointerAcquire
#pragma push_macro("InterlockedCompareExchangePointer")
#undef InterlockedCompareExchangePointer
#pragma push_macro("InterlockedCompareExchangePointerAcquire")
#undef InterlockedCompareExchangePointerAcquire
#pragma push_macro("InterlockedCompareExchangePointerRelease")
#undef InterlockedCompareExchangePointerRelease
#pragma push_macro("InterlockedCompareExchangePointerNoFence")
#undef InterlockedCompareExchangePointerNoFence
#pragma push_macro("InterlockedExchangeAddSizeT")
#undef InterlockedExchangeAddSizeT
#pragma push_macro("InterlockedExchangeAddSizeTAcquire")
#undef InterlockedExchangeAddSizeTAcquire
#pragma push_macro("InterlockedExchangeAddSizeTNoFence")
#undef InterlockedExchangeAddSizeTNoFence
#pragma push_macro("InterlockedIncrementSizeT")
#undef InterlockedIncrementSizeT
#pragma push_macro("InterlockedIncrementSizeTNoFence")
#undef InterlockedIncrementSizeTNoFence
#pragma push_macro("InterlockedDecrementSizeT")
#undef InterlockedDecrementSizeT
#pragma push_macro("InterlockedDecrementSizeTNoFence")
#undef InterlockedDecrementSizeTNoFence
#pragma push_macro("Yield")
#undef Yield
#pragma push_macro("CreateDirectory")
#undef CreateDirectory
#pragma push_macro("CaptureStackBackTrace")
#undef CaptureStackBackTrace
#pragma push_macro("GetObject")
#undef GetObject
