// Copyright (c) 2017 Computer Vision Center (CVC) at the Universitat Autonoma
// de Barcelona (UAB).
//
// This work is licensed under the terms of the MIT license.
// For a copy, see <https://opensource.org/licenses/MIT>.

#pragma once

#include "carla/rpc/Location.h"
#include "carla/sensor/s11n/LidarRawData.h"

#include <cstdint>
#include <vector>

namespace carla {
namespace sensor {
namespace s11n {

  /// Helper class to store and serialize the data generated by a Lidar.
  ///
  /// The header of a Lidar measurement consists of an array of uint32_t's in
  /// the following layout
  ///
  ///    {
  ///      Horizontal angle (float),
  ///      Channel count,
  ///      Point count of channel 0,
  ///      ...
  ///      Point count of channel n,
  ///    }
  ///
  /// The points are stored in an array of floats
  ///
  ///    {
  ///      X0, Y0, Z0, I0
  ///      ...
  ///      Xn, Yn, Zn, In
  ///    }
  ///

  class LidarDetection {
    public:
      geom::Location point;
      float intensity;

      LidarDetection() :
          point(0.0f, 0.0f, 0.0f), intensity{0.0f} { }
      LidarDetection(float x, float y, float z, float intensity) :
          point(x, y, z), intensity{intensity} { }
      LidarDetection(geom::Location p, float intensity) :
          point(p), intensity{intensity} { }

      void WritePlyHeaderInfo(std::ostream& out) const{
        out << "property float32 x\n" \
          "property float32 y\n" \
          "property float32 z\n" \
          "property float32 I\n";
      }

      void WriteDetection(std::ostream& out) const{
        out << point.x << ' ' << point.y << ' ' << point.z << ' ' << intensity;
      }
  };

  class LidarData : public LidarRawData{
    friend class LidarSerializer;
    friend class LidarHeaderView;

  public:
    explicit LidarData(uint32_t ChannelCount = 0u)
      : LidarRawData(ChannelCount) {
    }

    LidarData &operator=(LidarData &&) = default;

    void SaveDetections() {
      const uint32_t SizeLidarDetection = 4;
      _points.clear();
      _points.reserve(SizeLidarDetection * GetChannelCount() * _max_channel_points);

      for (auto idxChannel = 0u; idxChannel < GetChannelCount(); ++idxChannel) {
        _header[Index::SIZE + idxChannel] = static_cast<uint32_t>(_aux_points.size());
        for (auto& pt : _aux_points[idxChannel]) {
          _points.emplace_back(pt.point.x);
          _points.emplace_back(pt.point.y);
          _points.emplace_back(pt.point.z);
          _points.emplace_back(-1.0f); // FIXME Compute good Intensity here
        }
      }
    }

  private:
    std::vector<float> _points;

  };

} // namespace s11n
} // namespace sensor
} // namespace carla
