#!/bin/bash

#
# Copyright (C) 2018 Christoph Sommer <sommer@ccs-labs.org>
#
# Documentation for these modules is at http://veins.car2x.org/
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

set -e

echo ""
echo "-------------------------------------------------------------------------------"
echo "-- Removing directory ./veins-runall-output/*.out -----------------------------"
echo "-------------------------------------------------------------------------------"
rm -f veins-runall-output/*.out
echo ""
echo "-------------------------------------------------------------------------------"
echo "-- Running tests and collecting results ---------------------------------------"
echo "-------------------------------------------------------------------------------"
opp_runall /bin/sh ./run -d -- -c General -u Cmdenv "$@"
echo ""
echo "-------------------------------------------------------------------------------"
echo "-- Passed/skipped tests -------------------------------------------------------"
echo "-------------------------------------------------------------------------------"
cat veins-runall-output/*.out | egrep "^\[asserts-INFO\]" || echo "none."
echo ""
echo "-------------------------------------------------------------------------------"
echo "-- Failed tests----------------------------------------------------------------"
echo "-------------------------------------------------------------------------------"
cat veins-runall-output/*.out | egrep "^\[asserts-ERROR\]" && exit 1 || echo "none."
echo ""
