// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CarlaBoundingBox.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_CARLA_MSGS_MSG_CARLABOUNDINGBOX_H_
#define _FAST_DDS_GENERATED_CARLA_MSGS_MSG_CARLABOUNDINGBOX_H_

#include "geometry_msgs/msg/Vector3.h"

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(CarlaBoundingBox_SOURCE)
#define CarlaBoundingBox_DllAPI __declspec( dllexport )
#else
#define CarlaBoundingBox_DllAPI __declspec( dllimport )
#endif // CarlaBoundingBox_SOURCE
#else
#define CarlaBoundingBox_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define CarlaBoundingBox_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace carla_msgs {
    namespace msg {
        /*!
         * @brief This class represents the structure CarlaBoundingBox defined by the user in the IDL file.
         * @ingroup CARLABOUNDINGBOX
         */
        class CarlaBoundingBox
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport CarlaBoundingBox();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~CarlaBoundingBox();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object carla_msgs::msg::CarlaBoundingBox that will be copied.
             */
            eProsima_user_DllExport CarlaBoundingBox(
                    const CarlaBoundingBox& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object carla_msgs::msg::CarlaBoundingBox that will be copied.
             */
            eProsima_user_DllExport CarlaBoundingBox(
                    CarlaBoundingBox&& x);

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object carla_msgs::msg::CarlaBoundingBox that will be copied.
             */
            eProsima_user_DllExport CarlaBoundingBox& operator =(
                    const CarlaBoundingBox& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object carla_msgs::msg::CarlaBoundingBox that will be copied.
             */
            eProsima_user_DllExport CarlaBoundingBox& operator =(
                    CarlaBoundingBox&& x);

            /*!
             * @brief Comparison operator.
             * @param x carla_msgs::msg::CarlaBoundingBox object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const CarlaBoundingBox& x) const;

            /*!
             * @brief Comparison operator.
             * @param x carla_msgs::msg::CarlaBoundingBox object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const CarlaBoundingBox& x) const;

            /*!
             * @brief This function copies the value in member center
             * @param _center New value to be copied in member center
             */
            eProsima_user_DllExport void center(
                    const geometry_msgs::msg::Vector3& _center);

            /*!
             * @brief This function moves the value in member center
             * @param _center New value to be moved in member center
             */
            eProsima_user_DllExport void center(
                    geometry_msgs::msg::Vector3&& _center);

            /*!
             * @brief This function returns a constant reference to member center
             * @return Constant reference to member center
             */
            eProsima_user_DllExport const geometry_msgs::msg::Vector3& center() const;

            /*!
             * @brief This function returns a reference to member center
             * @return Reference to member center
             */
            eProsima_user_DllExport geometry_msgs::msg::Vector3& center();
            /*!
             * @brief This function copies the value in member size
             * @param _size New value to be copied in member size
             */
            eProsima_user_DllExport void size(
                    const geometry_msgs::msg::Vector3& _size);

            /*!
             * @brief This function moves the value in member size
             * @param _size New value to be moved in member size
             */
            eProsima_user_DllExport void size(
                    geometry_msgs::msg::Vector3&& _size);

            /*!
             * @brief This function returns a constant reference to member size
             * @return Constant reference to member size
             */
            eProsima_user_DllExport const geometry_msgs::msg::Vector3& size() const;

            /*!
             * @brief This function returns a reference to member size
             * @return Reference to member size
             */
            eProsima_user_DllExport geometry_msgs::msg::Vector3& size();

            /*!
             * @brief This function returns the maximum serialized size of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const carla_msgs::msg::CarlaBoundingBox& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            geometry_msgs::msg::Vector3 m_center;
            geometry_msgs::msg::Vector3 m_size;
        };
    } // namespace msg
} // namespace carla_msgs

#endif // _FAST_DDS_GENERATED_CARLA_MSGS_MSG_CARLABOUNDINGBOX_H_