name: Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install ruff yamllint
      - name: Run linters
        run: |
          python3 -m ruff check PythonAPI/
          python3 -m ruff format PythonAPI/ --check
          python3 -m yamllint -c .yamllint .
