name: UE5-PR

on:
  pull_request:
    branches:
      - ue5-dev
    types: [opened, synchronize, reopened]

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ubuntu-22-pr:
    name: Ubuntu 22.04 PR
    uses: ./.github/workflows/_ci-ubuntu.yml
    with:
      ubuntu-version: "22.04"
      python-versions: "3.10"
      smoke-test-python-versions: "3.10"
      additional-maps: false
      upload-package: false
      upload-replace-latest: false
      upload-docker: false

  ubuntu-24-pr:
    name: Ubuntu 24.04 PR
    uses: ./.github/workflows/_ci-ubuntu.yml
    with:
      ubuntu-version: "24.04"
      python-versions: "3.12"
      smoke-test-python-versions: "3.12"
      additional-maps: false
      upload-package: false
      upload-replace-latest: false
      upload-docker: false

  # windows-pr:
  #   name: Windows PR
  #   uses: ./.github/workflows/_ci-windows.yml
  #   with:
  #     python-versions: "3.12"
  #     additional-maps: false
  #     upload-package: false
  #     upload-replace-latest: false
